/**
 * Provisioning for the active build's spell caches.
 *
 * The spell caches are generated from the active build's SpellName.db2 and are
 * keyed by build, so a fresh clone has none and a build cutover leaves the new
 * build's cache empty. Without them every spell lookup answers "Not Found" -
 * an empty answer rather than an error, which is easy to miss. This module
 * detects that state and generates the caches so installation and first startup
 * produce a working server without a manual step.
 *
 * Generation is delegated to the same script `npm run generate:spell-cache`
 * runs, launched as a child process. That keeps its extensive console output
 * off this process's stdout, which for the MCP server carries JSON-RPC.
 *
 * @module version/SpellCacheProvisioner
 */

import * as fs from 'fs';
import * as path from 'path';
import { spawn } from 'child_process';
import { logger } from '../utils/logger';
import { getActiveBuild, resolveDataPath } from './BuildManifest';
import { readCacheMetadata } from '../utils/cache-metadata';

/** Cache files the spell tools require, relative to the build's cache dir. */
const SPELL_CACHE_FILES = ['spell_names_cache.json', 'spell_data_cache.json'] as const;

/** DB2 the caches are generated from. */
const SOURCE_DB2 = 'SpellName.db2';

/** Marks a generation run in progress, so two starts do not both generate. */
const LOCK_FILE = '.spell-cache-generating';

/**
 * A lock older than this is treated as abandoned. Generation takes minutes, so
 * the window is generous; a crashed run must not block provisioning forever.
 */
const LOCK_STALE_MS = 60 * 60 * 1000;

/** State of the active build's spell caches. */
export type SpellCacheState =
  /** Present and generated for the active build. */
  | 'ready'
  /** One or both cache files are absent. */
  | 'missing'
  /** Present but generated for a different build, so unusable. */
  | 'stale'
  /** Another process is generating them right now. */
  | 'generating';

export interface SpellCacheStatus {
  state: SpellCacheState;
  /** Build the caches must match. */
  build: number;
  /** Directory holding them. */
  cacheDir: string;
  /** One line explaining the state, suitable for a log or a tool response. */
  detail: string;
}

/**
 * Inspect the active build's spell caches.
 *
 * Reads only metadata sidecars, never the multi-megabyte cache bodies, so it is
 * cheap enough to call on every startup.
 *
 * @returns The current state and a human-readable explanation
 *
 * @example
 * ```typescript
 * const status = inspectSpellCache();
 * if (status.state !== 'ready') logger.warn(status.detail);
 * ```
 */
export function inspectSpellCache(): SpellCacheStatus {
  const activeBuild = getActiveBuild();
  const cacheDir = activeBuild.cacheDir;
  const base = { build: activeBuild.build, cacheDir };

  if (isGenerationInProgress(cacheDir)) {
    return {
      ...base,
      state: 'generating',
      detail: `Spell caches for build ${activeBuild.build} are being generated by another process.`,
    };
  }

  for (const fileName of SPELL_CACHE_FILES) {
    const filePath = path.join(cacheDir, fileName);

    if (!fs.existsSync(filePath)) {
      return {
        ...base,
        state: 'missing',
        detail: `Spell cache ${filePath} does not exist; build ${activeBuild.build} has no cached spell data.`,
      };
    }

    const meta = readCacheMetadata(filePath);
    if (!meta) {
      return {
        ...base,
        state: 'stale',
        detail: `Spell cache ${filePath} has no build metadata, so it cannot be trusted for build ${activeBuild.build}.`,
      };
    }
    if (meta.build !== activeBuild.build) {
      return {
        ...base,
        state: 'stale',
        detail: `Spell cache ${filePath} was generated for build ${meta.build}, not the active build ${activeBuild.build}.`,
      };
    }
  }

  return {
    ...base,
    state: 'ready',
    detail: `Spell caches for build ${activeBuild.build} are present and current.`,
  };
}

/** Whether SpellName.db2 is reachable, i.e. whether generation could succeed. */
export function isSpellCacheSourceAvailable(): boolean {
  try {
    return fs.existsSync(path.join(resolveDataPath('db2'), SOURCE_DB2));
  } catch {
    return false;
  }
}

function lockPath(cacheDir: string): string {
  return path.join(cacheDir, LOCK_FILE);
}

function isGenerationInProgress(cacheDir: string): boolean {
  const lock = lockPath(cacheDir);
  try {
    const stat = fs.statSync(lock);
    if (Date.now() - stat.mtimeMs > LOCK_STALE_MS) {
      fs.unlinkSync(lock); // abandoned by a crashed run
      return false;
    }
    return true;
  } catch {
    return false;
  }
}

/** Resolve the compiled generator script, or null when it is not built yet. */
function findGeneratorScript(): string | null {
  // __dirname is <root>/dist/version at runtime; the script sits beside it.
  const candidate = path.join(__dirname, '..', 'scripts', 'generate-spell-cache.js');
  return fs.existsSync(candidate) ? candidate : null;
}

export interface EnsureSpellCacheResult {
  /** Whether the caches are usable now. False while generation is still running. */
  ready: boolean;
  /** Whether this call started a generation run. */
  started: boolean;
  /** State observed before any action was taken. */
  initialState: SpellCacheState;
  /** One line describing what happened, suitable for a log. */
  detail: string;
  /** Resolves when a run started here finishes; absent if none was started. */
  completion?: Promise<boolean>;
}

export interface EnsureSpellCacheOptions {
  /**
   * Await generation instead of returning while it runs. Generation takes
   * several minutes, so callers that must not block - the MCP server's startup
   * among them - should leave this false and use `completion`.
   */
  wait?: boolean;
}

/**
 * Make sure the active build's spell caches exist, generating them if not.
 *
 * Does nothing when they are already current, when another process is already
 * generating them, or when SpellName.db2 is not reachable - a machine without
 * the client data cannot generate them, and failing there would break
 * installation for no gain.
 *
 * @param options.wait Await completion rather than returning while it runs
 * @returns What was observed and whether generation was started
 * @throws Never. Provisioning is best-effort: every failure is reported through
 *   the result and the log, because a missing cache must not stop the server
 *   from starting.
 *
 * @example
 * ```typescript
 * // At startup: kick generation off and carry on serving.
 * const result = await ensureSpellCache();
 * if (result.started) logger.info(result.detail);
 * ```
 */
export async function ensureSpellCache(
  options: EnsureSpellCacheOptions = {}
): Promise<EnsureSpellCacheResult> {
  const status = inspectSpellCache();

  if (status.state === 'ready') {
    return { ready: true, started: false, initialState: status.state, detail: status.detail };
  }

  if (status.state === 'generating') {
    return { ready: false, started: false, initialState: status.state, detail: status.detail };
  }

  if (!isSpellCacheSourceAvailable()) {
    let db2Dir = '<unresolved>';
    try {
      db2Dir = resolveDataPath('db2');
    } catch {
      // resolveDataPath throws only when no build resolves; the message below
      // is still the useful one.
    }
    return {
      ready: false,
      started: false,
      initialState: status.state,
      detail:
        `${status.detail} Cannot generate them: ${SOURCE_DB2} was not found in ${db2Dir}. ` +
        `Point the active build's db2 path at the client data, then run: npm run generate:spell-cache`,
    };
  }

  const script = findGeneratorScript();
  if (!script) {
    return {
      ready: false,
      started: false,
      initialState: status.state,
      detail:
        `${status.detail} The compiled generator is not present; build the project first, ` +
        `then run: npm run generate:spell-cache`,
    };
  }

  const completion = runGenerator(script, status.cacheDir, status.build);

  if (options.wait) {
    const ok = await completion;
    return {
      ready: ok,
      started: true,
      initialState: status.state,
      detail: ok
        ? `Generated spell caches for build ${status.build}.`
        : `Spell cache generation for build ${status.build} failed; see the log for the generator's output.`,
      completion,
    };
  }

  return {
    ready: false,
    started: true,
    initialState: status.state,
    detail:
      `${status.detail} Generating them in the background from ${SOURCE_DB2}; ` +
      `spell lookups return no data until it finishes.`,
    completion,
  };
}

/**
 * Run the generator as a child process, forwarding its output to the log.
 *
 * The child's stdout is piped and re-logged rather than inherited: this
 * process's stdout may be an MCP JSON-RPC stream, and the generator prints
 * progress freely.
 *
 * @param script Path to the compiled generator
 * @param cacheDir Directory the lock lives in
 * @param build Build being generated, for log messages
 * @returns Whether the generator exited successfully
 */
function runGenerator(script: string, cacheDir: string, build: number): Promise<boolean> {
  return new Promise<boolean>((resolve) => {
    const lock = lockPath(cacheDir);
    try {
      fs.mkdirSync(cacheDir, { recursive: true });
      fs.writeFileSync(lock, String(process.pid), 'utf8');
    } catch (error) {
      logger.error(`Could not claim the spell cache generation lock: ${error}`);
      resolve(false);
      return;
    }

    const releaseLock = (): void => {
      try {
        fs.unlinkSync(lock);
      } catch {
        // Already gone; nothing to release.
      }
    };


    logger.info(`Generating spell caches for build ${build}. This takes several minutes.`);

    const child = spawn(process.execPath, [script], {
      stdio: ['ignore', 'pipe', 'pipe'],
      env: process.env,
    });

    const forward = (chunk: Buffer): void => {
      for (const line of chunk.toString('utf8').split(/\r?\n/)) {
        if (line.trim()) {
          logger.info(`[spell-cache] ${line.trim()}`);
        }
      }
    };
    child.stdout.on('data', forward);
    child.stderr.on('data', forward);

    // If this process exits first the child is orphaned: nothing would release
    // the lock or observe the result, and the next start would race a generator
    // it cannot see. Stop it and clear the lock so that start re-detects the
    // work cleanly. Registered after the spawn so the child is in scope, and
    // removed on close so a long-lived host does not accumulate handlers.
    const onParentExit = (): void => {
      try {
        child.kill();
      } catch {
        // Already gone.
      }
      releaseLock();
    };
    process.once('exit', onParentExit);

    child.on('error', (error) => {
      logger.error(`Failed to start the spell cache generator: ${error.message}`);
      process.removeListener('exit', onParentExit);
      releaseLock();
      resolve(false);
    });

    child.on('close', (code) => {
      process.removeListener('exit', onParentExit);
      releaseLock();
      if (code === 0) {
        logger.info(`Spell caches for build ${build} are ready.`);
        resolve(true);
      } else {
        logger.error(`Spell cache generator exited with code ${code}.`);
        resolve(false);
      }
    });
  });
}
