/**
 * CastSpellHandler - Handles spell casting requests from bots
 *
 * Auto-generated by TrinityCore MCP Server
 * Generation date: 2025-11-01T10:01:47.741Z
 * Template: packet_handler.hbs
 *
 * Opcode: CMSG_CAST_SPELL
 * Direction: client
 * Thread-safety: Packet-based (thread-safe)
 */

#pragma once

#include "Session/BotSession.h"
#include "WorldPacket.h"
#include "Packets/SpellPacketBuilder.h"

namespace Playerbot::Packets {

/**
 * CastSpellHandler
 * Handles spell casting requests from bots
 *
 * Handles: CMSG_CAST_SPELL
 * Size: 21 bytes (fixed)
 * Frequency: Low (&lt;1 Hz)
 */
class CastSpellHandler {
public:
    /**
     * Handle incoming packet
     * @param session Bot session receiving the packet
     * @param packet Packet data
     */
    static void Handle(BotSession* session, WorldPacket& packet);

    /**
     * Build outgoing packet
     * @param session Bot session sending the packet
     * @return Constructed packet ready to send
     */
    static WorldPacket Build(BotSession* session);

private:
    // Packet structure
    struct PacketData {
        ObjectGuid casterGuid;  // GUID of casting unit
        uint32 spellId;  // Spell ID to cast
        ObjectGuid targetGuid;  // GUID of target unit
        uint8 castFlags;  // Casting flags
    };

    // Helper methods
    static bool ValidatePacket(const PacketData& data);
    static void ProcessPacket(BotSession* session, const PacketData& data);

    static void LogPacket(const PacketData& data, bool incoming);
};

} // namespace Playerbot::Packets

// Implementation
namespace Playerbot::Packets {

void CastSpellHandler::Handle(BotSession* session, WorldPacket& packet) {
    if (!session || !session->GetBot())
        return;

    PacketData data;

    // Read packet fields
    packet >> data.casterGuid;
    packet >> data.spellId;
        packet >> data.targetGuid;
    packet >> data.castFlags;

    LogPacket(data, true);

    // Validate packet data
    if (!ValidatePacket(data)) {
        TC_LOG_ERROR("playerbot", "CastSpellHandler: Invalid packet data from bot {}",
                     session->GetBot()->GetName());
        return;
    }

    // Process packet
    ProcessPacket(session, data);
}

WorldPacket CastSpellHandler::Build(BotSession* session) {
    WorldPacket packet(CMSG_CAST_SPELL, 21);

    PacketData data;

    // Write packet fields
    packet << data.casterGuid;
    packet << data.spellId;
        packet << data.targetGuid;
    packet << data.castFlags;

    LogPacket(data, false);

    return packet;
}

bool CastSpellHandler::ValidatePacket(const PacketData& data) {
    // Validate packet fields
    if (!(data.casterGuid.IsEmpty())) {
        TC_LOG_ERROR("playerbot", "CastSpellHandler: Validation failed - Invalid casterGuid");
        return false;
    }
    if (!(data.spellId &#x3D;&#x3D; 0)) {
        TC_LOG_ERROR("playerbot", "CastSpellHandler: Validation failed - Invalid spellId");
        return false;
    }
    if (!(data.targetGuid.IsEmpty())) {
        TC_LOG_ERROR("playerbot", "CastSpellHandler: Validation failed - Invalid targetGuid");
        return false;
    }
    return true;
}

void CastSpellHandler::ProcessPacket(BotSession* session, const PacketData& data) {
    Player* bot = session->GetBot();
    if (!bot)
        return;

    // Default packet processing
    TC_LOG_DEBUG("playerbot", "CastSpellHandler: Processing packet for bot {}", bot->GetName());


    // Handle spell cast
    if (data.spellId) {
        SpellPacketBuilder builder;
        builder.CastSpell(bot, data.spellId, data.target);
    }


}

void CastSpellHandler::LogPacket(const PacketData& data, bool incoming) {
    std::string direction = incoming ? "RECV" : "SEND";
    TC_LOG_TRACE("playerbot.packets", "{} CMSG_CAST_SPELL:", direction);
    TC_LOG_TRACE("playerbot.packets", "  casterGuid: {}", data.casterGuid.ToString());
    TC_LOG_TRACE("playerbot.packets", "  spellId: {}", data.spellId);
        TC_LOG_TRACE("playerbot.packets", "  targetGuid: {}", data.targetGuid.ToString());
    TC_LOG_TRACE("playerbot.packets", "  castFlags: {}", data.castFlags);
    }

} // namespace Playerbot::Packets
