/**
 * TrinityCore SAI Unified Editor - Enhanced Simulator
 *
 * Complete event/action type coverage for professional debugging.
 * Phase 3 implementation with full TrinityCore smart_scripts support.
 *
 * @module sai-unified/simulator-enhanced
 * @version 3.0.0
 */

import { SAISimulator, SimulationState, SimulationEvent } from './simulator';
import { SAINode } from './types';

// ============================================================================
// COMPLETE EVENT TYPE DEFINITIONS
// ============================================================================

export interface EventTypeDefinition {
  id: string;
  name: string;
  description: string;
  category: 'update' | 'combat' | 'health' | 'mana' | 'spell' | 'movement' | 'misc';
  condition: (state: SimulationState, node: SAINode) => boolean;
  paramDescriptions?: string[];
}

export const EVENT_TYPES: Record<string, EventTypeDefinition> = {
  '0': {
    id: '0',
    name: 'UPDATE_IC',
    description: 'Update in combat',
    category: 'update',
    condition: (state) => state.inCombat,
    paramDescriptions: ['InitialMin', 'InitialMax', 'RepeatMin', 'RepeatMax'],
  },
  '1': {
    id: '1',
    name: 'UPDATE_OOC',
    description: 'Update out of combat',
    category: 'update',
    condition: (state) => !state.inCombat,
    paramDescriptions: ['InitialMin', 'InitialMax', 'RepeatMin', 'RepeatMax'],
  },
  '2': {
    id: '2',
    name: 'HEALTH_PCT',
    description: 'Health percentage',
    category: 'health',
    condition: (state, node) => {
      const minPct = (node.parameters[0]?.value as number) || 0;
      const maxPct = (node.parameters[1]?.value as number) || 100;
      return state.healthPercent >= minPct && state.healthPercent <= maxPct;
    },
    paramDescriptions: ['MinPercent', 'MaxPercent', 'RepeatMin', 'RepeatMax'],
  },
  '3': {
    id: '3',
    name: 'MANA_PCT',
    description: 'Mana percentage',
    category: 'mana',
    condition: (state, node) => {
      const minPct = (node.parameters[0]?.value as number) || 0;
      const maxPct = (node.parameters[1]?.value as number) || 100;
      return state.manaPercent >= minPct && state.manaPercent <= maxPct;
    },
    paramDescriptions: ['MinPercent', 'MaxPercent', 'RepeatMin', 'RepeatMax'],
  },
  '4': {
    id: '4',
    name: 'AGGRO',
    description: 'On entering combat',
    category: 'combat',
    condition: (state) => state.inCombat,
  },
  '5': {
    id: '5',
    name: 'KILL',
    description: 'On killing a unit',
    category: 'combat',
    condition: (state) => state.inCombat,
    paramDescriptions: ['CooldownMin', 'CooldownMax', 'PlayerOnly', 'CreatureID'],
  },
  '6': {
    id: '6',
    name: 'DEATH',
    description: 'On creature death',
    category: 'combat',
    condition: (state) => state.healthPercent <= 0,
  },
  '7': {
    id: '7',
    name: 'EVADE',
    description: 'On evade (reset)',
    category: 'combat',
    condition: (state) => !state.inCombat,
  },
  '8': {
    id: '8',
    name: 'SPELLHIT',
    description: 'On spell hit',
    category: 'spell',
    condition: (state) => state.inCombat,
    paramDescriptions: ['SpellID', 'SchoolMask', 'CooldownMin', 'CooldownMax'],
  },
  '9': {
    id: '9',
    name: 'RANGE',
    description: 'On target in range',
    category: 'movement',
    condition: (state) => state.inCombat,
    paramDescriptions: ['MinDist', 'MaxDist', 'RepeatMin', 'RepeatMax'],
  },
  '10': {
    id: '10',
    name: 'OOC_LOS',
    description: 'Out of combat line of sight',
    category: 'movement',
    condition: (state) => !state.inCombat,
    paramDescriptions: ['Hostile', 'MaxRange', 'CooldownMin', 'CooldownMax'],
  },
  '11': {
    id: '11',
    name: 'RESPAWN',
    description: 'On respawn',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['MapID', 'AreaID'],
  },
  '12': {
    id: '12',
    name: 'TARGET_HEALTH_PCT',
    description: 'Target health percentage',
    category: 'health',
    condition: (state, node) => {
      const minPct = (node.parameters[0]?.value as number) || 0;
      const maxPct = (node.parameters[1]?.value as number) || 100;
      // Simplified: use own health as proxy
      return state.healthPercent >= minPct && state.healthPercent <= maxPct;
    },
    paramDescriptions: ['MinPercent', 'MaxPercent', 'RepeatMin', 'RepeatMax'],
  },
  '13': {
    id: '13',
    name: 'TARGET_CASTING',
    description: 'Target casting spell',
    category: 'spell',
    condition: (state) => state.inCombat,
    paramDescriptions: ['RepeatMin', 'RepeatMax'],
  },
  '14': {
    id: '14',
    name: 'FRIENDLY_HEALTH',
    description: 'Friendly unit health',
    category: 'health',
    condition: (state, node) => {
      const minPct = (node.parameters[1]?.value as number) || 0;
      const maxPct = (node.parameters[2]?.value as number) || 100;
      return state.healthPercent >= minPct && state.healthPercent <= maxPct;
    },
    paramDescriptions: ['Radius', 'MinPercent', 'MaxPercent', 'RepeatMin', 'RepeatMax'],
  },
  '15': {
    id: '15',
    name: 'FRIENDLY_IS_CC',
    description: 'Friendly crowd controlled',
    category: 'misc',
    condition: (state) => state.inCombat,
    paramDescriptions: ['Radius', 'RepeatMin', 'RepeatMax'],
  },
  '16': {
    id: '16',
    name: 'FRIENDLY_MISSING_BUFF',
    description: 'Friendly missing buff',
    category: 'spell',
    condition: (state) => state.inCombat,
    paramDescriptions: ['SpellID', 'Radius', 'RepeatMin', 'RepeatMax'],
  },
  '17': {
    id: '17',
    name: 'SUMMONED_UNIT',
    description: 'On summoned unit',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['CreatureID', 'CooldownMin', 'CooldownMax'],
  },
  '18': {
    id: '18',
    name: 'TARGET_MANA_PCT',
    description: 'Target mana percentage',
    category: 'mana',
    condition: (state, node) => {
      const minPct = (node.parameters[0]?.value as number) || 0;
      const maxPct = (node.parameters[1]?.value as number) || 100;
      return state.manaPercent >= minPct && state.manaPercent <= maxPct;
    },
    paramDescriptions: ['MinPercent', 'MaxPercent', 'RepeatMin', 'RepeatMax'],
  },
  '19': {
    id: '19',
    name: 'ACCEPTED_QUEST',
    description: 'On quest accepted',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['QuestID'],
  },
  '20': {
    id: '20',
    name: 'REWARD_QUEST',
    description: 'On quest rewarded',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['QuestID'],
  },
  '21': {
    id: '21',
    name: 'REACHED_HOME',
    description: 'On reached home',
    category: 'movement',
    condition: (state) => !state.inCombat,
  },
  '22': {
    id: '22',
    name: 'RECEIVE_EMOTE',
    description: 'On receive emote',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['EmoteID', 'CooldownMin', 'CooldownMax', 'Condition', 'ConditionValue'],
  },
  '23': {
    id: '23',
    name: 'HAS_AURA',
    description: 'Has aura',
    category: 'spell',
    condition: (state) => state.inCombat,
    paramDescriptions: ['SpellID', 'Stacks', 'RepeatMin', 'RepeatMax'],
  },
  '24': {
    id: '24',
    name: 'TARGET_BUFFED',
    description: 'Target has aura',
    category: 'spell',
    condition: (state) => state.inCombat,
    paramDescriptions: ['SpellID', 'Stacks', 'RepeatMin', 'RepeatMax'],
  },
  '25': {
    id: '25',
    name: 'RESET',
    description: 'On AI reset (evade)',
    category: 'combat',
    condition: (state) => !state.inCombat,
  },
  '26': {
    id: '26',
    name: 'IC_LOS',
    description: 'In combat line of sight',
    category: 'movement',
    condition: (state) => state.inCombat,
    paramDescriptions: ['Hostile', 'MaxRange', 'CooldownMin', 'CooldownMax'],
  },
  '27': {
    id: '27',
    name: 'PASSENGER_BOARDED',
    description: 'Passenger boarded',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['CooldownMin', 'CooldownMax'],
  },
  '28': {
    id: '28',
    name: 'PASSENGER_REMOVED',
    description: 'Passenger removed',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['CooldownMin', 'CooldownMax'],
  },
  '29': {
    id: '29',
    name: 'CHARMED',
    description: 'On charmed',
    category: 'misc',
    condition: () => true,
  },
  '30': {
    id: '30',
    name: 'CHARMED_TARGET',
    description: 'Charmed target',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['RepeatMin', 'RepeatMax'],
  },
  '31': {
    id: '31',
    name: 'SPELLHIT_TARGET',
    description: 'Target hit by spell',
    category: 'spell',
    condition: (state) => state.inCombat,
    paramDescriptions: ['SpellID', 'SchoolMask', 'RepeatMin', 'RepeatMax'],
  },
  '32': {
    id: '32',
    name: 'DAMAGED',
    description: 'On damaged',
    category: 'combat',
    condition: (state) => state.inCombat,
    paramDescriptions: ['MinDmg', 'MaxDmg', 'RepeatMin', 'RepeatMax'],
  },
  '33': {
    id: '33',
    name: 'DAMAGED_TARGET',
    description: 'Target damaged',
    category: 'combat',
    condition: (state) => state.inCombat,
    paramDescriptions: ['MinDmg', 'MaxDmg', 'RepeatMin', 'RepeatMax'],
  },
  '34': {
    id: '34',
    name: 'MOVEMENTINFORM',
    description: 'Movement inform',
    category: 'movement',
    condition: () => true,
    paramDescriptions: ['MovementType', 'PointID'],
  },
  '35': {
    id: '35',
    name: 'SUMMON_DESPAWNED',
    description: 'Summon despawned',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['Entry', 'CooldownMin', 'CooldownMax'],
  },
  '36': {
    id: '36',
    name: 'CORPSE_REMOVED',
    description: 'Corpse removed',
    category: 'misc',
    condition: () => true,
  },
  '37': {
    id: '37',
    name: 'AI_INIT',
    description: 'AI initialized',
    category: 'misc',
    condition: () => true,
  },
  '38': {
    id: '38',
    name: 'DATA_SET',
    description: 'Data set',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['Field', 'Value', 'CooldownMin', 'CooldownMax'],
  },
  '39': {
    id: '39',
    name: 'WAYPOINT_START',
    description: 'Waypoint started',
    category: 'movement',
    condition: () => true,
    paramDescriptions: ['PointID', 'PathID'],
  },
  '40': {
    id: '40',
    name: 'WAYPOINT_REACHED',
    description: 'Waypoint reached',
    category: 'movement',
    condition: () => true,
    paramDescriptions: ['PointID', 'PathID'],
  },
  '41': {
    id: '41',
    name: 'TRANSPORT_ADDPLAYER',
    description: 'Transport add player',
    category: 'misc',
    condition: () => true,
  },
  '42': {
    id: '42',
    name: 'TRANSPORT_ADDCREATURE',
    description: 'Transport add creature',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['Entry'],
  },
  '43': {
    id: '43',
    name: 'TRANSPORT_REMOVE_PLAYER',
    description: 'Transport remove player',
    category: 'misc',
    condition: () => true,
  },
  '44': {
    id: '44',
    name: 'TRANSPORT_RELOCATE',
    description: 'Transport relocated',
    category: 'movement',
    condition: () => true,
    paramDescriptions: ['PointID'],
  },
  '45': {
    id: '45',
    name: 'INSTANCE_PLAYER_ENTER',
    description: 'Instance player entered',
    category: 'misc',
    condition: () => true,
  },
  '46': {
    id: '46',
    name: 'AREATRIGGER_ONTRIGGER',
    description: 'Area trigger triggered',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['AreaTriggerID'],
  },
  '47': {
    id: '47',
    name: 'QUEST_ACCEPTED',
    description: 'Quest accepted (duplicate of 19)',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['QuestID'],
  },
  '48': {
    id: '48',
    name: 'QUEST_OBJ_COMPLETION',
    description: 'Quest objective completed',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['QuestID'],
  },
  '49': {
    id: '49',
    name: 'QUEST_COMPLETION',
    description: 'Quest completed',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['QuestID'],
  },
  '50': {
    id: '50',
    name: 'QUEST_REWARDED',
    description: 'Quest rewarded (duplicate of 20)',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['QuestID'],
  },
  '51': {
    id: '51',
    name: 'QUEST_FAIL',
    description: 'Quest failed',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['QuestID'],
  },
  '52': {
    id: '52',
    name: 'TEXT_OVER',
    description: 'Text over',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['GroupID'],
  },
  '53': {
    id: '53',
    name: 'RECEIVE_HEAL',
    description: 'On receive heal',
    category: 'health',
    condition: (state) => state.inCombat,
    paramDescriptions: ['MinHeal', 'MaxHeal', 'RepeatMin', 'RepeatMax'],
  },
  '54': {
    id: '54',
    name: 'JUST_SUMMONED',
    description: 'Just summoned',
    category: 'misc',
    condition: () => true,
  },
  '55': {
    id: '55',
    name: 'WAYPOINT_PAUSED',
    description: 'Waypoint paused',
    category: 'movement',
    condition: () => true,
    paramDescriptions: ['PointID', 'PathID'],
  },
  '56': {
    id: '56',
    name: 'WAYPOINT_RESUMED',
    description: 'Waypoint resumed',
    category: 'movement',
    condition: () => true,
    paramDescriptions: ['PointID', 'PathID'],
  },
  '57': {
    id: '57',
    name: 'WAYPOINT_STOPPED',
    description: 'Waypoint stopped',
    category: 'movement',
    condition: () => true,
    paramDescriptions: ['PointID', 'PathID'],
  },
  '58': {
    id: '58',
    name: 'WAYPOINT_ENDED',
    description: 'Waypoint ended',
    category: 'movement',
    condition: () => true,
    paramDescriptions: ['PointID', 'PathID'],
  },
  '59': {
    id: '59',
    name: 'TIMED_EVENT_TRIGGERED',
    description: 'Timed event triggered',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['EventID'],
  },
  '60': {
    id: '60',
    name: 'UPDATE',
    description: 'Update (always)',
    category: 'update',
    condition: () => true,
    paramDescriptions: ['InitialMin', 'InitialMax', 'RepeatMin', 'RepeatMax'],
  },
  '61': {
    id: '61',
    name: 'LINK',
    description: 'Link (internal use)',
    category: 'misc',
    condition: () => true,
  },
  '62': {
    id: '62',
    name: 'GOSSIP_SELECT',
    description: 'Gossip option selected',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['MenuID', 'OptionID'],
  },
  '63': {
    id: '63',
    name: 'JUST_CREATED',
    description: 'Just created',
    category: 'misc',
    condition: () => true,
  },
  '64': {
    id: '64',
    name: 'GOSSIP_HELLO',
    description: 'Gossip hello',
    category: 'misc',
    condition: () => true,
  },
  '65': {
    id: '65',
    name: 'FOLLOW_COMPLETED',
    description: 'Follow completed',
    category: 'movement',
    condition: () => true,
  },
  '66': {
    id: '66',
    name: 'DUMMY_EFFECT',
    description: 'Spell dummy effect',
    category: 'spell',
    condition: () => true,
    paramDescriptions: ['SpellID', 'EffectIndex'],
  },
  '67': {
    id: '67',
    name: 'IS_BEHIND_TARGET',
    description: 'Is behind target',
    category: 'movement',
    condition: (state) => state.inCombat,
    paramDescriptions: ['CooldownMin', 'CooldownMax'],
  },
  '68': {
    id: '68',
    name: 'GAME_EVENT_START',
    description: 'Game event started',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['GameEventID'],
  },
  '69': {
    id: '69',
    name: 'GAME_EVENT_END',
    description: 'Game event ended',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['GameEventID'],
  },
  '70': {
    id: '70',
    name: 'GO_STATE_CHANGED',
    description: 'GameObject state changed',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['State'],
  },
  '71': {
    id: '71',
    name: 'GO_EVENT_INFORM',
    description: 'GameObject event inform',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['EventID'],
  },
  '72': {
    id: '72',
    name: 'ACTION_DONE',
    description: 'Action done',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['EventID'],
  },
  '73': {
    id: '73',
    name: 'ON_SPELLCLICK',
    description: 'On spell click',
    category: 'misc',
    condition: () => true,
  },
  '74': {
    id: '74',
    name: 'FRIENDLY_HEALTH_PCT',
    description: 'Friendly health percentage',
    category: 'health',
    condition: (state, node) => {
      const minPct = (node.parameters[1]?.value as number) || 0;
      const maxPct = (node.parameters[2]?.value as number) || 100;
      return state.healthPercent >= minPct && state.healthPercent <= maxPct;
    },
    paramDescriptions: ['Radius', 'MinPercent', 'MaxPercent', 'RepeatMin', 'RepeatMax'],
  },
  '75': {
    id: '75',
    name: 'DISTANCE_CREATURE',
    description: 'Distance to creature',
    category: 'movement',
    condition: () => true,
    paramDescriptions: ['GUID', 'Entry', 'Distance', 'Repeat'],
  },
  '76': {
    id: '76',
    name: 'DISTANCE_GAMEOBJECT',
    description: 'Distance to gameobject',
    category: 'movement',
    condition: () => true,
    paramDescriptions: ['GUID', 'Entry', 'Distance', 'Repeat'],
  },
  '77': {
    id: '77',
    name: 'COUNTER_SET',
    description: 'Counter set',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['CounterID', 'Value', 'CooldownMin', 'CooldownMax'],
  },
  '78': {
    id: '78',
    name: 'SCENE_START',
    description: 'Scene started',
    category: 'misc',
    condition: () => true,
  },
  '79': {
    id: '79',
    name: 'SCENE_TRIGGER',
    description: 'Scene trigger',
    category: 'misc',
    condition: () => true,
  },
  '80': {
    id: '80',
    name: 'SCENE_CANCEL',
    description: 'Scene cancelled',
    category: 'misc',
    condition: () => true,
  },
  '81': {
    id: '81',
    name: 'SCENE_COMPLETE',
    description: 'Scene completed',
    category: 'misc',
    condition: () => true,
  },
  '82': {
    id: '82',
    name: 'SUMMONED_UNIT_DIES',
    description: 'Summoned unit dies',
    category: 'misc',
    condition: () => true,
    paramDescriptions: ['CreatureID', 'CooldownMin', 'CooldownMax'],
  },
};

// ============================================================================
// ACTION TYPE DEFINITIONS
// ============================================================================

export interface ActionTypeDefinition {
  id: string;
  name: string;
  description: string;
  category: 'talk' | 'combat' | 'movement' | 'spell' | 'summon' | 'state' | 'misc';
  execute: (state: SimulationState, node: SAINode) => Partial<SimulationState>;
  paramDescriptions?: string[];
}

export const ACTION_TYPES: Record<string, ActionTypeDefinition> = {
  '1': {
    id: '1',
    name: 'TALK',
    description: 'Say text',
    category: 'talk',
    execute: () => ({}),
    paramDescriptions: ['TextGroupID', 'Duration', 'UseTalkTarget'],
  },
  '2': {
    id: '2',
    name: 'SET_FACTION',
    description: 'Set faction',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['FactionID'],
  },
  '3': {
    id: '3',
    name: 'MORPH_TO_ENTRY_OR_MODEL',
    description: 'Morph',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['CreatureEntry', 'ModelID'],
  },
  '4': {
    id: '4',
    name: 'SOUND',
    description: 'Play sound',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['SoundID', 'OnlySelf', 'Distance'],
  },
  '5': {
    id: '5',
    name: 'PLAY_EMOTE',
    description: 'Play emote',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['EmoteID'],
  },
  '6': {
    id: '6',
    name: 'FAIL_QUEST',
    description: 'Fail quest',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['QuestID'],
  },
  '7': {
    id: '7',
    name: 'OFFER_QUEST',
    description: 'Offer quest',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['QuestID', 'DirectAdd'],
  },
  '8': {
    id: '8',
    name: 'SET_REACT_STATE',
    description: 'Set react state',
    category: 'combat',
    execute: () => ({}),
    paramDescriptions: ['State'],
  },
  '9': {
    id: '9',
    name: 'ACTIVATE_GOBJECT',
    description: 'Activate gameobject',
    category: 'misc',
    execute: () => ({}),
  },
  '10': {
    id: '10',
    name: 'RANDOM_EMOTE',
    description: 'Random emote',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['Emote1', 'Emote2', 'Emote3', 'Emote4', 'Emote5', 'Emote6'],
  },
  '11': {
    id: '11',
    name: 'CAST',
    description: 'Cast spell',
    category: 'spell',
    execute: () => ({}),
    paramDescriptions: ['SpellID', 'Flags'],
  },
  '12': {
    id: '12',
    name: 'SUMMON_CREATURE',
    description: 'Summon creature',
    category: 'summon',
    execute: () => ({}),
    paramDescriptions: ['CreatureID', 'SummonType', 'Duration', 'StorageID', 'AttackInvoker'],
  },
  '13': {
    id: '13',
    name: 'THREAT_SINGLE_PCT',
    description: 'Threat single percent',
    category: 'combat',
    execute: () => ({}),
    paramDescriptions: ['Percent', 'IncDec'],
  },
  '14': {
    id: '14',
    name: 'THREAT_ALL_PCT',
    description: 'Threat all percent',
    category: 'combat',
    execute: () => ({}),
    paramDescriptions: ['Percent', 'IncDec'],
  },
  '15': {
    id: '15',
    name: 'CALL_AREAEXPLOREDOREVENTHAPPENS',
    description: 'Quest credit',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['QuestID'],
  },
  '16': {
    id: '16',
    name: 'SET_EMOTE_STATE',
    description: 'Set emote state',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['EmoteID'],
  },
  '17': {
    id: '17',
    name: 'SET_UNIT_FLAG',
    description: 'Set unit flag',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['Flags', 'Type'],
  },
  '18': {
    id: '18',
    name: 'REMOVE_UNIT_FLAG',
    description: 'Remove unit flag',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['Flags', 'Type'],
  },
  '19': {
    id: '19',
    name: 'AUTO_ATTACK',
    description: 'Auto attack',
    category: 'combat',
    execute: () => ({}),
    paramDescriptions: ['AllowAttackState'],
  },
  '20': {
    id: '20',
    name: 'ALLOW_COMBAT_MOVEMENT',
    description: 'Combat movement',
    category: 'combat',
    execute: () => ({}),
    paramDescriptions: ['AllowCombatMovement'],
  },
  '21': {
    id: '21',
    name: 'SET_EVENT_PHASE',
    description: 'Set event phase',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['Phase'],
  },
  '22': {
    id: '22',
    name: 'INC_EVENT_PHASE',
    description: 'Increment phase',
    category: 'state',
    execute: (state, node) => {
      const increment = (node.parameters[0]?.value as number) || 1;
      const newPhase = Math.min(12, state.phase + increment);
      return { phase: newPhase };
    },
    paramDescriptions: ['Increment', 'Decrement'],
  },
  '23': {
    id: '23',
    name: 'EVADE',
    description: 'Evade',
    category: 'combat',
    execute: (state) => ({ inCombat: false }),
  },
  '24': {
    id: '24',
    name: 'FLEE_FOR_ASSIST',
    description: 'Flee for assist',
    category: 'combat',
    execute: () => ({}),
  },
  '25': {
    id: '25',
    name: 'CALL_GROUPEVENTHAPPENS',
    description: 'Quest group credit',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['QuestID'],
  },
  '26': {
    id: '26',
    name: 'COMBAT_STOP',
    description: 'Stop combat',
    category: 'combat',
    execute: (state) => ({ inCombat: false }),
  },
  '27': {
    id: '27',
    name: 'REMOVEAURASFROMSPELL',
    description: 'Remove auras',
    category: 'spell',
    execute: () => ({}),
    paramDescriptions: ['SpellID', 'Charges'],
  },
  '28': {
    id: '28',
    name: 'FOLLOW',
    description: 'Follow',
    category: 'movement',
    execute: () => ({}),
    paramDescriptions: ['Distance', 'Angle', 'EndCreatureEntry', 'Credit', 'CreditType'],
  },
  '29': {
    id: '29',
    name: 'RANDOM_PHASE',
    description: 'Random phase',
    category: 'state',
    execute: (state, node) => {
      const phases = [
        node.parameters[0]?.value,
        node.parameters[1]?.value,
        node.parameters[2]?.value,
        node.parameters[3]?.value,
        node.parameters[4]?.value,
        node.parameters[5]?.value,
      ].filter((p) => p && p > 0) as number[];

      if (phases.length > 0) {
        const randomPhase = phases[Math.floor(Math.random() * phases.length)];
        return { phase: randomPhase };
      }
      return {};
    },
    paramDescriptions: ['Phase1', 'Phase2', 'Phase3', 'Phase4', 'Phase5', 'Phase6'],
  },
  '30': {
    id: '30',
    name: 'RANDOM_PHASE_RANGE',
    description: 'Random phase range',
    category: 'state',
    execute: (state, node) => {
      const minPhase = (node.parameters[0]?.value as number) || 1;
      const maxPhase = (node.parameters[1]?.value as number) || 12;
      const randomPhase = Math.floor(Math.random() * (maxPhase - minPhase + 1)) + minPhase;
      return { phase: randomPhase };
    },
    paramDescriptions: ['PhaseMin', 'PhaseMax'],
  },
  '31': {
    id: '31',
    name: 'RESET_GOBJECT',
    description: 'Reset gameobject',
    category: 'misc',
    execute: () => ({}),
  },
  '32': {
    id: '32',
    name: 'CALL_KILLEDMONSTER',
    description: 'Kill credit',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['CreatureEntry'],
  },
  '33': {
    id: '33',
    name: 'SET_INST_DATA',
    description: 'Set instance data',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['Field', 'Data', 'Type'],
  },
  '34': {
    id: '34',
    name: 'SET_INST_DATA64',
    description: 'Set instance data 64',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['Field'],
  },
  '35': {
    id: '35',
    name: 'UPDATE_TEMPLATE',
    description: 'Update template',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['Entry', 'Team'],
  },
  '36': {
    id: '36',
    name: 'DIE',
    description: 'Die',
    category: 'combat',
    execute: (state) => ({ healthPercent: 0 }),
  },
  '37': {
    id: '37',
    name: 'SET_IN_COMBAT_WITH_ZONE',
    description: 'Combat with zone',
    category: 'combat',
    execute: (state) => ({ inCombat: true }),
  },
  '38': {
    id: '38',
    name: 'CALL_FOR_HELP',
    description: 'Call for help',
    category: 'combat',
    execute: () => ({}),
    paramDescriptions: ['Radius', 'WithEmote'],
  },
  '39': {
    id: '39',
    name: 'SET_SHEATH',
    description: 'Set sheath',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['Sheath'],
  },
  '40': {
    id: '40',
    name: 'FORCE_DESPAWN',
    description: 'Force despawn',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['Timer', 'ForceRespawnTimer'],
  },
  '41': {
    id: '41',
    name: 'SET_INVINCIBILITY_HP_LEVEL',
    description: 'Set invincibility HP',
    category: 'combat',
    execute: () => ({}),
    paramDescriptions: ['MinHPValue', 'Percent'],
  },
  '42': {
    id: '42',
    name: 'MOUNT_TO_ENTRY_OR_MODEL',
    description: 'Mount',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['CreatureEntry', 'ModelID'],
  },
  '43': {
    id: '43',
    name: 'SET_INGAME_PHASE_MASK',
    description: 'Set phase mask',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['PhaseMask'],
  },
  '44': {
    id: '44',
    name: 'SET_DATA',
    description: 'Set data',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['Field', 'Data'],
  },
  '45': {
    id: '45',
    name: 'ATTACK_STOP',
    description: 'Stop attack',
    category: 'combat',
    execute: () => ({}),
  },
  '46': {
    id: '46',
    name: 'SET_VISIBILITY',
    description: 'Set visibility',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['Visibility'],
  },
  '47': {
    id: '47',
    name: 'SET_ACTIVE',
    description: 'Set active',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['Active'],
  },
  '48': {
    id: '48',
    name: 'ATTACK_START',
    description: 'Start attack',
    category: 'combat',
    execute: (state) => ({ inCombat: true }),
  },
  '49': {
    id: '49',
    name: 'SUMMON_GO',
    description: 'Summon gameobject',
    category: 'summon',
    execute: () => ({}),
    paramDescriptions: ['Entry', 'DespawnTime'],
  },
  '50': {
    id: '50',
    name: 'KILL_UNIT',
    description: 'Kill unit',
    category: 'combat',
    execute: () => ({}),
  },
  '51': {
    id: '51',
    name: 'ACTIVATE_TAXI',
    description: 'Activate taxi',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['TaxiID'],
  },
  '52': {
    id: '52',
    name: 'WP_START',
    description: 'Start waypoint',
    category: 'movement',
    execute: () => ({}),
    paramDescriptions: ['Run', 'PathID', 'Repeat', 'ReactState'],
  },
  '53': {
    id: '53',
    name: 'WP_PAUSE',
    description: 'Pause waypoint',
    category: 'movement',
    execute: () => ({}),
    paramDescriptions: ['Time'],
  },
  '54': {
    id: '54',
    name: 'WP_STOP',
    description: 'Stop waypoint',
    category: 'movement',
    execute: () => ({}),
    paramDescriptions: ['DespawnTime', 'QuestID', 'Fail'],
  },
  '55': {
    id: '55',
    name: 'ADD_ITEM',
    description: 'Add item',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['ItemID', 'Count'],
  },
  '56': {
    id: '56',
    name: 'REMOVE_ITEM',
    description: 'Remove item',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['ItemID', 'Count'],
  },
  '57': {
    id: '57',
    name: 'INSTALL_AI_TEMPLATE',
    description: 'Install AI template',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['AITemplate'],
  },
  '58': {
    id: '58',
    name: 'SET_RUN',
    description: 'Set run',
    category: 'movement',
    execute: () => ({}),
    paramDescriptions: ['Run'],
  },
  '59': {
    id: '59',
    name: 'SET_DISABLE_GRAVITY',
    description: 'Disable gravity',
    category: 'movement',
    execute: () => ({}),
    paramDescriptions: ['Disable'],
  },
  '60': {
    id: '60',
    name: 'SET_SWIM',
    description: 'Set swim',
    category: 'movement',
    execute: () => ({}),
    paramDescriptions: ['Swim'],
  },
  '61': {
    id: '61',
    name: 'TELEPORT',
    description: 'Teleport',
    category: 'movement',
    execute: () => ({}),
    paramDescriptions: ['MapID'],
  },
  '62': {
    id: '62',
    name: 'SET_COUNTER',
    description: 'Set counter',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['CounterID', 'Value', 'Reset'],
  },
  '63': {
    id: '63',
    name: 'STORE_TARGET_LIST',
    description: 'Store target list',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['VariableID'],
  },
  '64': {
    id: '64',
    name: 'WP_RESUME',
    description: 'Resume waypoint',
    category: 'movement',
    execute: () => ({}),
  },
  '65': {
    id: '65',
    name: 'SET_ORIENTATION',
    description: 'Set orientation',
    category: 'movement',
    execute: () => ({}),
    paramDescriptions: ['Orientation'],
  },
  '66': {
    id: '66',
    name: 'CREATE_TIMED_EVENT',
    description: 'Create timed event',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['InitMin', 'InitMax', 'RepeatMin', 'RepeatMax', 'Chance'],
  },
  '67': {
    id: '67',
    name: 'PLAYMOVIE',
    description: 'Play movie',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['MovieID'],
  },
  '68': {
    id: '68',
    name: 'MOVE_TO_POS',
    description: 'Move to position',
    category: 'movement',
    execute: () => ({}),
    paramDescriptions: ['PointID', 'Transport', 'Melee'],
  },
  '69': {
    id: '69',
    name: 'RESPAWN_TARGET',
    description: 'Respawn target',
    category: 'misc',
    execute: () => ({}),
  },
  '70': {
    id: '70',
    name: 'EQUIP',
    description: 'Equip',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['Entry', 'Mask', 'Slot1', 'Slot2', 'Slot3'],
  },
  '71': {
    id: '71',
    name: 'CLOSE_GOSSIP',
    description: 'Close gossip',
    category: 'misc',
    execute: () => ({}),
  },
  '72': {
    id: '72',
    name: 'TRIGGER_TIMED_EVENT',
    description: 'Trigger timed event',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['EventID'],
  },
  '73': {
    id: '73',
    name: 'REMOVE_TIMED_EVENT',
    description: 'Remove timed event',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['EventID'],
  },
  '74': {
    id: '74',
    name: 'ADD_AURA',
    description: 'Add aura',
    category: 'spell',
    execute: () => ({}),
    paramDescriptions: ['SpellID'],
  },
  '75': {
    id: '75',
    name: 'OVERRIDE_SCRIPT_BASE_OBJECT',
    description: 'Override script base',
    category: 'misc',
    execute: () => ({}),
  },
  '76': {
    id: '76',
    name: 'RESET_SCRIPT_BASE_OBJECT',
    description: 'Reset script base',
    category: 'misc',
    execute: () => ({}),
  },
  '77': {
    id: '77',
    name: 'CALL_SCRIPT_RESET',
    description: 'Call script reset',
    category: 'misc',
    execute: () => ({}),
  },
  '78': {
    id: '78',
    name: 'SET_RANGED_MOVEMENT',
    description: 'Set ranged movement',
    category: 'combat',
    execute: () => ({}),
    paramDescriptions: ['Distance', 'Angle'],
  },
  '79': {
    id: '79',
    name: 'CALL_TIMED_ACTIONLIST',
    description: 'Call timed actionlist',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['EntryOrGuid'],
  },
  '80': {
    id: '80',
    name: 'SET_NPC_FLAG',
    description: 'Set NPC flag',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['Flags', 'Type'],
  },
  '81': {
    id: '81',
    name: 'ADD_NPC_FLAG',
    description: 'Add NPC flag',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['Flags', 'Type'],
  },
  '82': {
    id: '82',
    name: 'REMOVE_NPC_FLAG',
    description: 'Remove NPC flag',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['Flags', 'Type'],
  },
  '83': {
    id: '83',
    name: 'SIMPLE_TALK',
    description: 'Simple talk',
    category: 'talk',
    execute: () => ({}),
    paramDescriptions: ['TextGroupID', 'Duration', 'UseTalkTarget'],
  },
  '84': {
    id: '84',
    name: 'INVOKER_CAST',
    description: 'Invoker cast',
    category: 'spell',
    execute: () => ({}),
    paramDescriptions: ['SpellID', 'Flags'],
  },
  '85': {
    id: '85',
    name: 'CROSS_CAST',
    description: 'Cross cast',
    category: 'spell',
    execute: () => ({}),
    paramDescriptions: ['SpellID', 'Flags', 'TargetType', 'TargetParam1', 'TargetParam2', 'TargetParam3'],
  },
  '86': {
    id: '86',
    name: 'CALL_RANDOM_TIMED_ACTIONLIST',
    description: 'Random timed actionlist',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['Entry1', 'Entry2', 'Entry3', 'Entry4', 'Entry5', 'Entry6'],
  },
  '87': {
    id: '87',
    name: 'CALL_RANDOM_RANGE_TIMED_ACTIONLIST',
    description: 'Random range actionlist',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['IDMin', 'IDMax'],
  },
  '88': {
    id: '88',
    name: 'RANDOM_MOVE',
    description: 'Random move',
    category: 'movement',
    execute: () => ({}),
    paramDescriptions: ['Distance'],
  },
  '89': {
    id: '89',
    name: 'SET_UNIT_FIELD_BYTES_1',
    description: 'Set unit bytes 1',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['Bytes', 'Type'],
  },
  '90': {
    id: '90',
    name: 'REMOVE_UNIT_FIELD_BYTES_1',
    description: 'Remove unit bytes 1',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['Bytes', 'Type'],
  },
  '91': {
    id: '91',
    name: 'INTERRUPT_SPELL',
    description: 'Interrupt spell',
    category: 'spell',
    execute: () => ({}),
    paramDescriptions: ['WithDelayed', 'SpellType'],
  },
  '92': {
    id: '92',
    name: 'SEND_GO_CUSTOM_ANIM',
    description: 'Send GO custom anim',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['AnimID'],
  },
  '93': {
    id: '93',
    name: 'SET_DYNAMIC_FLAG',
    description: 'Set dynamic flag',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['Flags'],
  },
  '94': {
    id: '94',
    name: 'ADD_DYNAMIC_FLAG',
    description: 'Add dynamic flag',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['Flags'],
  },
  '95': {
    id: '95',
    name: 'REMOVE_DYNAMIC_FLAG',
    description: 'Remove dynamic flag',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['Flags'],
  },
  '96': {
    id: '96',
    name: 'JUMP_TO_POS',
    description: 'Jump to position',
    category: 'movement',
    execute: () => ({}),
    paramDescriptions: ['SpeedXY', 'SpeedZ', 'PointID'],
  },
  '97': {
    id: '97',
    name: 'SEND_GOSSIP_MENU',
    description: 'Send gossip menu',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['GossipMenuID', 'TextID'],
  },
  '98': {
    id: '98',
    name: 'GO_SET_LOOT_STATE',
    description: 'Set GO loot state',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['State'],
  },
  '99': {
    id: '99',
    name: 'SEND_TARGET_TO_TARGET',
    description: 'Send target to target',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['TargetID'],
  },
  '100': {
    id: '100',
    name: 'SET_HOME_POS',
    description: 'Set home position',
    category: 'movement',
    execute: () => ({}),
  },
  '101': {
    id: '101',
    name: 'SET_HEALTH_REGEN',
    description: 'Set health regen',
    category: 'combat',
    execute: () => ({}),
    paramDescriptions: ['Toggle'],
  },
  '102': {
    id: '102',
    name: 'SET_ROOT',
    description: 'Set root',
    category: 'movement',
    execute: () => ({}),
    paramDescriptions: ['Root'],
  },
  '103': {
    id: '103',
    name: 'SET_GO_FLAG',
    description: 'Set GO flag',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['Flags'],
  },
  '104': {
    id: '104',
    name: 'ADD_GO_FLAG',
    description: 'Add GO flag',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['Flags'],
  },
  '105': {
    id: '105',
    name: 'REMOVE_GO_FLAG',
    description: 'Remove GO flag',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['Flags'],
  },
  '106': {
    id: '106',
    name: 'SUMMON_CREATURE_GROUP',
    description: 'Summon creature group',
    category: 'summon',
    execute: () => ({}),
    paramDescriptions: ['GroupID', 'AttackInvoker'],
  },
  '107': {
    id: '107',
    name: 'SET_POWER',
    description: 'Set power',
    category: 'combat',
    execute: (state, node) => {
      const powerType = (node.parameters[0]?.value as number) || 0;
      const newPower = (node.parameters[1]?.value as number) || 0;

      if (powerType === 0) { // Mana
        return { manaPercent: newPower };
      }
      return {};
    },
    paramDescriptions: ['PowerType', 'NewPower'],
  },
  '108': {
    id: '108',
    name: 'ADD_POWER',
    description: 'Add power',
    category: 'combat',
    execute: (state, node) => {
      const powerType = (node.parameters[0]?.value as number) || 0;
      const addPower = (node.parameters[1]?.value as number) || 0;

      if (powerType === 0) { // Mana
        return { manaPercent: Math.min(100, state.manaPercent + addPower) };
      }
      return {};
    },
    paramDescriptions: ['PowerType', 'AddPower'],
  },
  '109': {
    id: '109',
    name: 'REMOVE_POWER',
    description: 'Remove power',
    category: 'combat',
    execute: (state, node) => {
      const powerType = (node.parameters[0]?.value as number) || 0;
      const removePower = (node.parameters[1]?.value as number) || 0;

      if (powerType === 0) { // Mana
        return { manaPercent: Math.max(0, state.manaPercent - removePower) };
      }
      return {};
    },
    paramDescriptions: ['PowerType', 'RemovePower'],
  },
  '110': {
    id: '110',
    name: 'GAME_EVENT_STOP',
    description: 'Stop game event',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['GameEventID'],
  },
  '111': {
    id: '111',
    name: 'GAME_EVENT_START',
    description: 'Start game event',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['GameEventID'],
  },
  '112': {
    id: '112',
    name: 'START_CLOSEST_WAYPOINT',
    description: 'Start closest waypoint',
    category: 'movement',
    execute: () => ({}),
    paramDescriptions: ['WP1', 'WP2', 'WP3', 'WP4', 'WP5', 'WP6'],
  },
  '113': {
    id: '113',
    name: 'MOVE_OFFSET',
    description: 'Move offset',
    category: 'movement',
    execute: () => ({}),
    paramDescriptions: ['PointID'],
  },
  '114': {
    id: '114',
    name: 'RANDOM_SOUND',
    description: 'Random sound',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['Sound1', 'Sound2', 'Sound3', 'Sound4', 'OnlySelf', 'Distance'],
  },
  '115': {
    id: '115',
    name: 'SET_CORPSE_DELAY',
    description: 'Set corpse delay',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['Timer'],
  },
  '116': {
    id: '116',
    name: 'DISABLE_EVADE',
    description: 'Disable evade',
    category: 'combat',
    execute: () => ({}),
    paramDescriptions: ['Disable'],
  },
  '117': {
    id: '117',
    name: 'GO_SET_GO_STATE',
    description: 'Set GO state',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['State'],
  },
  '118': {
    id: '118',
    name: 'SET_CAN_FLY',
    description: 'Set can fly',
    category: 'movement',
    execute: () => ({}),
    paramDescriptions: ['Fly'],
  },
  '119': {
    id: '119',
    name: 'REMOVE_AURAS_BY_TYPE',
    description: 'Remove auras by type',
    category: 'spell',
    execute: () => ({}),
    paramDescriptions: ['AuraType'],
  },
  '120': {
    id: '120',
    name: 'SET_SIGHT_DIST',
    description: 'Set sight distance',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['Distance'],
  },
  '121': {
    id: '121',
    name: 'FLEE',
    description: 'Flee',
    category: 'combat',
    execute: () => ({}),
    paramDescriptions: ['FleeTime'],
  },
  '122': {
    id: '122',
    name: 'ADD_THREAT',
    description: 'Add threat',
    category: 'combat',
    execute: () => ({}),
    paramDescriptions: ['Threat'],
  },
  '123': {
    id: '123',
    name: 'LOAD_EQUIPMENT',
    description: 'Load equipment',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['EquipmentID', 'Force'],
  },
  '124': {
    id: '124',
    name: 'TRIGGER_RANDOM_TIMED_EVENT',
    description: 'Trigger random timed event',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['MinID', 'MaxID'],
  },
  '125': {
    id: '125',
    name: 'REMOVE_ALL_GAMEOBJECTS',
    description: 'Remove all gameobjects',
    category: 'misc',
    execute: () => ({}),
  },
  '126': {
    id: '126',
    name: 'STOP_MOTION',
    description: 'Stop motion',
    category: 'movement',
    execute: () => ({}),
    paramDescriptions: ['StopMoving', 'MovementExpired'],
  },
  '127': {
    id: '127',
    name: 'PLAY_ANIMKIT',
    description: 'Play anim kit',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['AnimKitID', 'Type'],
  },
  '128': {
    id: '128',
    name: 'SCENE_PLAY',
    description: 'Play scene',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['SceneID'],
  },
  '129': {
    id: '129',
    name: 'SCENE_CANCEL',
    description: 'Cancel scene',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['SceneID'],
  },
  '130': {
    id: '130',
    name: 'SPAWN_SPAWNGROUP',
    description: 'Spawn group',
    category: 'summon',
    execute: () => ({}),
    paramDescriptions: ['GroupID', 'MinDelay', 'MaxDelay', 'Flags'],
  },
  '131': {
    id: '131',
    name: 'DESPAWN_SPAWNGROUP',
    description: 'Despawn group',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['GroupID', 'MinDelay', 'MaxDelay', 'Flags'],
  },
  '132': {
    id: '132',
    name: 'RESPAWN_BY_SPAWNID',
    description: 'Respawn by spawn ID',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['SpawnType', 'SpawnID'],
  },
  '133': {
    id: '133',
    name: 'INVOKER_CAST_DEST',
    description: 'Invoker cast at dest',
    category: 'spell',
    execute: () => ({}),
    paramDescriptions: ['SpellID', 'Flags'],
  },
  '134': {
    id: '134',
    name: 'PLAY_CINEMATIC',
    description: 'Play cinematic',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['CinematicID'],
  },
  '135': {
    id: '135',
    name: 'SET_MOVEMENT_SPEED',
    description: 'Set movement speed',
    category: 'movement',
    execute: () => ({}),
    paramDescriptions: ['MovementType', 'SpeedMod'],
  },
  '136': {
    id: '136',
    name: 'PLAY_SPELL_VISUAL_KIT',
    description: 'Play spell visual kit',
    category: 'spell',
    execute: () => ({}),
    paramDescriptions: ['SpellVisualKitID', 'KitType', 'Duration'],
  },
  '137': {
    id: '137',
    name: 'OVERRIDE_LIGHT',
    description: 'Override light',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['ZoneID', 'OverrideLightID', 'TransitionMs'],
  },
  '138': {
    id: '138',
    name: 'OVERRIDE_WEATHER',
    description: 'Override weather',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['ZoneID', 'WeatherState', 'Intensity'],
  },
  '139': {
    id: '139',
    name: 'SET_AI_ANIM_KIT',
    description: 'Set AI anim kit',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['AnimKitID'],
  },
  '140': {
    id: '140',
    name: 'SET_HOVER',
    description: 'Set hover',
    category: 'movement',
    execute: () => ({}),
    paramDescriptions: ['Enable'],
  },
  '141': {
    id: '141',
    name: 'SET_HEALTH_PCT',
    description: 'Set health percent',
    category: 'combat',
    execute: (state, node) => {
      const healthPct = (node.parameters[0]?.value as number) || 100;
      return { healthPercent: Math.max(0, Math.min(100, healthPct)) };
    },
    paramDescriptions: ['Percent'],
  },
  '142': {
    id: '142',
    name: 'CREATE_CONVERSATION',
    description: 'Create conversation',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['ConversationID'],
  },
  '143': {
    id: '143',
    name: 'SET_IMMUNE_PC',
    description: 'Set immune to PC',
    category: 'combat',
    execute: () => ({}),
    paramDescriptions: ['Immune'],
  },
  '144': {
    id: '144',
    name: 'SET_IMMUNE_NPC',
    description: 'Set immune to NPC',
    category: 'combat',
    execute: () => ({}),
    paramDescriptions: ['Immune'],
  },
  '145': {
    id: '145',
    name: 'SET_UNINTERACTIBLE',
    description: 'Set uninteractible',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['Uninteractible'],
  },
  '146': {
    id: '146',
    name: 'ACTIVATE_GAMEOBJECT',
    description: 'Activate gameobject',
    category: 'misc',
    execute: () => ({}),
  },
  '147': {
    id: '147',
    name: 'ADD_TO_STORED_TARGET_LIST',
    description: 'Add to stored targets',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['VariableID'],
  },
  '148': {
    id: '148',
    name: 'BECOME_PERSONAL_CLONE_FOR_PLAYER',
    description: 'Become personal clone',
    category: 'state',
    execute: () => ({}),
    paramDescriptions: ['Type', 'Duration'],
  },
  '149': {
    id: '149',
    name: 'TRIGGER_GAME_EVENT',
    description: 'Trigger game event',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['GameEventID', 'UseSaiTargetAsGameEventSource'],
  },
  '150': {
    id: '150',
    name: 'DO_ACTION',
    description: 'Do action',
    category: 'misc',
    execute: () => ({}),
    paramDescriptions: ['ActionID'],
  },
};

/**
 * Get event type definition
 */
export function getEventTypeDefinition(typeId: string): EventTypeDefinition | undefined {
  return EVENT_TYPES[typeId];
}

/**
 * Get action type definition
 */
export function getActionTypeDefinition(typeId: string): ActionTypeDefinition | undefined {
  return ACTION_TYPES[typeId];
}

/**
 * Get all event types by category
 */
export function getEventTypesByCategory(category: EventTypeDefinition['category']): EventTypeDefinition[] {
  return Object.values(EVENT_TYPES).filter((e) => e.category === category);
}

/**
 * Get all action types by category
 */
export function getActionTypesByCategory(category: ActionTypeDefinition['category']): ActionTypeDefinition[] {
  return Object.values(ACTION_TYPES).filter((a) => a.category === category);
}
