/**
 * Environment Variable Utilities
 *
 * Utilities for reading and writing .env.local file
 */

import fs from 'fs';
import path from 'path';

const ENV_FILE_PATH = path.join(process.cwd(), '.env.local');

/**
 * Parse .env file content into key-value pairs
 */
export function parseEnvFile(content: string): Record<string, string> {
  const env: Record<string, string> = {};

  content.split('\n').forEach(line => {
    line = line.trim();

    // Skip comments and empty lines
    if (!line || line.startsWith('#')) {
      return;
    }

    // Parse KEY=VALUE format
    const match = line.match(/^([^=]+)=(.*)$/);
    if (match) {
      const key = match[1].trim();
      let value = match[2].trim();

      // Remove quotes if present
      if ((value.startsWith('"') && value.endsWith('"')) ||
          (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }

      env[key] = value;
    }
  });

  return env;
}

/**
 * Read environment variables from .env.local file
 */
export function readEnvFile(): Record<string, string> {
  try {
    if (!fs.existsSync(ENV_FILE_PATH)) {
      return {};
    }

    const content = fs.readFileSync(ENV_FILE_PATH, 'utf-8');
    return parseEnvFile(content);
  } catch (error) {
    console.error('Error reading .env.local:', error);
    return {};
  }
}

/**
 * Write environment variables to .env.local file
 */
export function writeEnvFile(env: Record<string, string>): void {
  try {
    const lines: string[] = [
      '# TrinityCore MCP Web-UI Configuration',
      '# Auto-generated by Settings Dashboard',
      `# Last updated: ${new Date().toISOString()}`,
      '',
    ];

    // Group by category for better organization
    const categories = {
      'Database Configuration': ['DB_HOST', 'DB_PORT', 'DB_USERNAME', 'DB_PASSWORD', 'DB_WORLD_DATABASE', 'DB_AUTH_DATABASE', 'DB_CHARACTERS_DATABASE'],
      'TrinityCore Data Paths': ['TRINITY_ROOT', 'GT_PATH', 'DBC_PATH', 'DB2_PATH', 'VMAP_PATH', 'MMAP_PATH', 'MAP_FILES_PATH'],
      'MCP Server Configuration': ['MCP_HOST', 'MCP_PORT'],
      'WebSocket Configuration': ['WEBSOCKET_PORT', 'WEBSOCKET_MAX_CLIENTS', 'WEBSOCKET_HEARTBEAT_INTERVAL', 'WEBSOCKET_TIMEOUT_MS', 'WEBSOCKET_RATE_LIMIT'],
      'Testing Configuration': ['TESTING_ENABLED', 'TESTING_AUTO_GENERATE', 'TESTING_COVERAGE_THRESHOLD', 'TESTING_PERFORMANCE_BASELINES'],
      'Logging Configuration': ['LOG_LEVEL', 'LOG_CONSOLE', 'LOG_FILE', 'LOG_FILE_PATH', 'LOG_MAX_FILE_SIZE', 'LOG_MAX_FILES'],
      'SOAP API Configuration': ['TRINITY_SOAP_HOST', 'TRINITY_SOAP_PORT', 'TRINITY_SOAP_USERNAME', 'TRINITY_SOAP_PASSWORD', 'TRINITY_SOAP_MOCK'],
    };

    for (const [category, keys] of Object.entries(categories)) {
      const categoryVars = keys.filter(key => env[key] !== undefined);
      if (categoryVars.length > 0) {
        lines.push(`# ${category}`);
        lines.push(...Array(70).fill('=').join(''));
        lines.push('');

        for (const key of categoryVars) {
          const value = env[key];
          // Quote values that contain spaces or special characters
          const needsQuotes = /\s|[#$&]/.test(value);
          lines.push(`${key}=${needsQuotes ? `"${value}"` : value}`);
        }

        lines.push('');
      }
    }

    // Add any remaining variables not in categories
    const categorizedKeys = new Set(Object.values(categories).flat());
    const remaining = Object.keys(env).filter(key => !categorizedKeys.has(key));
    if (remaining.length > 0) {
      lines.push('# Other Configuration');
      lines.push(...Array(70).fill('=').join(''));
      lines.push('');
      for (const key of remaining) {
        const value = env[key];
        const needsQuotes = /\s|[#$&]/.test(value);
        lines.push(`${key}=${needsQuotes ? `"${value}"` : value}`);
      }
      lines.push('');
    }

    fs.writeFileSync(ENV_FILE_PATH, lines.join('\n'), 'utf-8');
  } catch (error) {
    console.error('Error writing .env.local:', error);
    throw new Error(`Failed to write .env.local: ${(error as Error).message}`);
  }
}

/**
 * Reload environment variables from .env.local into process.env
 * Note: This only affects the current Node.js process
 */
export function reloadEnvVars(): void {
  const envVars = readEnvFile();
  Object.assign(process.env, envVars);
}

/**
 * Check if .env.local file exists
 */
export function envFileExists(): boolean {
  return fs.existsSync(ENV_FILE_PATH);
}
