/**
 * Environment Variable Utilities
 *
 * Utilities for reading and writing .env files
 * Manages both:
 * - web-ui/.env.local (for Next.js web-ui)
 * - root .env (for MCP server)
 */

import fs from 'fs';
import path from 'path';

const WEB_UI_ENV_PATH = path.join(process.cwd(), '.env.local');
const MCP_SERVER_ENV_PATH = path.join(process.cwd(), '..', '.env');

/**
 * Parse .env file content into key-value pairs
 */
export function parseEnvFile(content: string): Record<string, string> {
  const env: Record<string, string> = {};

  content.split('\n').forEach(line => {
    line = line.trim();

    // Skip comments and empty lines
    if (!line || line.startsWith('#')) {
      return;
    }

    // Parse KEY=VALUE format
    const match = line.match(/^([^=]+)=(.*)$/);
    if (match) {
      const key = match[1].trim();
      let value = match[2].trim();

      // Remove quotes if present
      if ((value.startsWith('"') && value.endsWith('"')) ||
          (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }

      env[key] = value;
    }
  });

  return env;
}

/**
 * Read environment variables from a specific .env file
 */
export function readEnvFile(filePath: string = WEB_UI_ENV_PATH): Record<string, string> {
  try {
    if (!fs.existsSync(filePath)) {
      return {};
    }

    const content = fs.readFileSync(filePath, 'utf-8');
    return parseEnvFile(content);
  } catch (error) {
    console.error(`Error reading ${filePath}:`, error);
    return {};
  }
}

/**
 * Read from web-ui .env.local
 */
export function readWebUIEnv(): Record<string, string> {
  return readEnvFile(WEB_UI_ENV_PATH);
}

/**
 * Read from MCP server .env
 */
export function readMCPServerEnv(): Record<string, string> {
  return readEnvFile(MCP_SERVER_ENV_PATH);
}

/**
 * Read from both .env files and merge (web-ui takes precedence)
 */
export function readAllEnvFiles(): { webUI: Record<string, string>; mcpServer: Record<string, string>; merged: Record<string, string> } {
  const webUI = readWebUIEnv();
  const mcpServer = readMCPServerEnv();
  const merged = { ...mcpServer, ...webUI };

  return { webUI, mcpServer, merged };
}

/**
 * Write environment variables to a specific .env file
 */
function writeEnvFileInternal(env: Record<string, string>, filePath: string, header: string): void {
  try {
    const lines: string[] = [
      header,
      '# Auto-generated by Settings Dashboard',
      `# Last updated: ${new Date().toISOString()}`,
      '',
    ];

    // Group by category for better organization
    const categories = {
      'Database Configuration': ['DB_HOST', 'DB_PORT', 'DB_USERNAME', 'DB_PASSWORD', 'DB_WORLD_DATABASE', 'DB_AUTH_DATABASE', 'DB_CHARACTERS_DATABASE'],
      'TrinityCore Data Paths': ['TRINITY_ROOT', 'WOW_PATH', 'GT_PATH', 'DBC_PATH', 'DB2_PATH', 'VMAP_PATH', 'MMAP_PATH', 'MAP_FILES_PATH'],
      'MCP Server Configuration': ['MCP_HOST', 'MCP_PORT'],
      'WebSocket Configuration': ['WEBSOCKET_PORT', 'WEBSOCKET_MAX_CLIENTS', 'WEBSOCKET_HEARTBEAT_INTERVAL', 'WEBSOCKET_TIMEOUT_MS', 'WEBSOCKET_RATE_LIMIT'],
      'Testing Configuration': ['TESTING_ENABLED', 'TESTING_AUTO_GENERATE', 'TESTING_COVERAGE_THRESHOLD', 'TESTING_PERFORMANCE_BASELINES'],
      'Logging Configuration': ['LOG_LEVEL', 'LOG_CONSOLE', 'LOG_FILE', 'LOG_FILE_PATH', 'LOG_MAX_FILE_SIZE', 'LOG_MAX_FILES'],
      'SOAP API Configuration': ['TRINITY_SOAP_HOST', 'TRINITY_SOAP_PORT', 'TRINITY_SOAP_USERNAME', 'TRINITY_SOAP_PASSWORD', 'TRINITY_SOAP_MOCK'],
    };

    for (const [category, keys] of Object.entries(categories)) {
      const categoryVars = keys.filter(key => env[key] !== undefined);
      if (categoryVars.length > 0) {
        lines.push(`# ${category}`);
        lines.push(Array(70).fill('=').join(''));
        lines.push('');

        for (const key of categoryVars) {
          const value = env[key];
          // Quote values that contain spaces or special characters
          const needsQuotes = /\s|[#$&]/.test(value);
          lines.push(`${key}=${needsQuotes ? `"${value}"` : value}`);
        }

        lines.push('');
      }
    }

    // Add any remaining variables not in categories
    const categorizedKeys = new Set(Object.values(categories).flat());
    const remaining = Object.keys(env).filter(key => !categorizedKeys.has(key));
    if (remaining.length > 0) {
      lines.push('# Other Configuration');
      lines.push(Array(70).fill('=').join(''));
      lines.push('');
      for (const key of remaining) {
        const value = env[key];
        const needsQuotes = /\s|[#$&]/.test(value);
        lines.push(`${key}=${needsQuotes ? `"${value}"` : value}`);
      }
      lines.push('');
    }

    fs.writeFileSync(filePath, lines.join('\n'), 'utf-8');
  } catch (error) {
    console.error(`Error writing ${filePath}:`, error);
    throw new Error(`Failed to write ${filePath}: ${(error as Error).message}`);
  }
}

/**
 * Write to web-ui .env.local file
 */
export function writeWebUIEnv(env: Record<string, string>): void {
  writeEnvFileInternal(env, WEB_UI_ENV_PATH, '# TrinityCore MCP Web-UI Configuration');
}

/**
 * Write to MCP server .env file
 */
export function writeMCPServerEnv(env: Record<string, string>): void {
  // Convert web-ui env var names to MCP server format
  const mcpEnv: Record<string, string> = {};

  // Map web-ui names to MCP server names
  const mapping: Record<string, string> = {
    'DB_HOST': 'TRINITY_DB_HOST',
    'DB_PORT': 'TRINITY_DB_PORT',
    'DB_USERNAME': 'TRINITY_DB_USER',
    'DB_PASSWORD': 'TRINITY_DB_PASSWORD',
    'DB_WORLD_DATABASE': 'TRINITY_DB_WORLD',
    'DB_AUTH_DATABASE': 'TRINITY_DB_AUTH',
    'DB_CHARACTERS_DATABASE': 'TRINITY_DB_CHARACTERS',
  };

  // Apply mappings
  for (const [webKey, mcpKey] of Object.entries(mapping)) {
    if (env[webKey] !== undefined) {
      mcpEnv[mcpKey] = env[webKey];
    }
  }

  // Copy other vars directly
  const directCopyKeys = ['TRINITY_ROOT', 'WOW_PATH', 'GT_PATH', 'DBC_PATH', 'DB2_PATH', 'VMAP_PATH', 'MMAP_PATH', 'MCP_PORT', 'MCP_HOST'];
  for (const key of directCopyKeys) {
    if (env[key] !== undefined) {
      mcpEnv[key] = env[key];
    }
  }

  writeEnvFileInternal(mcpEnv, MCP_SERVER_ENV_PATH, '# TrinityCore MCP Server Configuration');
}

/**
 * Write to both .env files (web-ui and MCP server)
 */
export function writeAllEnvFiles(env: Record<string, string>): void {
  writeWebUIEnv(env);
  writeMCPServerEnv(env);
}

/**
 * Reload environment variables from .env files into process.env
 * Note: This only affects the current Node.js process (Next.js server)
 */
export function reloadEnvVars(): void {
  const { merged } = readAllEnvFiles();
  Object.assign(process.env, merged);
}

/**
 * Check if .env files exist
 */
export function envFileExists(): { webUI: boolean; mcpServer: boolean } {
  return {
    webUI: fs.existsSync(WEB_UI_ENV_PATH),
    mcpServer: fs.existsSync(MCP_SERVER_ENV_PATH),
  };
}
