/**
 * ⚠️ DEPRECATED - DO NOT USE ⚠️
 *
 * This file is DEPRECATED and will be removed in a future version.
 *
 * Please migrate to the new unified SAI editor:
 * - Location: @/lib/sai-unified/
 * - Components: @/components/sai-editor/
 * - Documentation: /docs/SAI_EDITOR_USER_GUIDE.md
 * - Migration Guide: Run `npx ts-node scripts/migrate-sai-editor.ts`
 *
 * New features in unified editor:
 * - AI-powered generation (GPT-4, Claude, Ollama, LM Studio)
 * - Real-time database validation
 * - Collaborative editing
 * - 12+ pre-built templates
 * - Performance optimizations
 * - Comprehensive testing
 *
 * @deprecated Use @/lib/sai-unified/ instead
 * @see /docs/SAI_EDITOR_USER_GUIDE.md
 */

/**
 * Complete TrinityCore Smart AI (SAI) Editor Utilities
 *
 * Contains ALL SAI event, action, and target types from TrinityCore master branch.
 * Source: SmartScriptMgr.h from TrinityCore/TrinityCore GitHub repository
 *
 * This file provides comprehensive SAI type definitions for the Visual SAI Editor.
 */

/**
 * COMPLETE SAI Event Types (0-90) - ALL TrinityCore Events
 */
export const SAI_EVENT_TYPES_COMPLETE = [
  { id: '0', name: 'UPDATE_IC', label: 'Update In Combat', params: ['InitialMin', 'InitialMax', 'RepeatMin', 'RepeatMax'] },
  { id: '1', name: 'UPDATE_OOC', label: 'Update Out of Combat', params: ['InitialMin', 'InitialMax', 'RepeatMin', 'RepeatMax'] },
  { id: '2', name: 'HEALTH_PCT', label: 'Health Percentage', params: ['HPMin%', 'HPMax%', 'RepeatMin', 'RepeatMax'] },
  { id: '3', name: 'MANA_PCT', label: 'Mana Percentage', params: ['ManaMin%', 'ManaMax%', 'RepeatMin', 'RepeatMax'] },
  { id: '4', name: 'AGGRO', label: 'On Aggro', params: [] },
  { id: '5', name: 'KILL', label: 'On Kill', params: ['CooldownMin', 'CooldownMax'] },
  { id: '6', name: 'DEATH', label: 'On Death', params: [] },
  { id: '7', name: 'EVADE', label: 'On Evade', params: [] },
  { id: '8', name: 'SPELLHIT', label: 'On Spell Hit', params: ['SpellID', 'School', 'CooldownMin', 'CooldownMax'] },
  { id: '9', name: 'RANGE', label: 'On Range', params: ['MinDist', 'MaxDist', 'RepeatMin', 'RepeatMax'] },
  { id: '10', name: 'OOC_LOS', label: 'OOC Line of Sight', params: ['HostileCrew', 'MaxRange', 'CooldownMin', 'CooldownMax'] },
  { id: '11', name: 'RESPAWN', label: 'On Respawn', params: [] },
  { id: '12', name: 'TARGET_HEALTH_PCT', label: 'Target Health Percentage', params: ['HPMin%', 'HPMax%', 'RepeatMin', 'RepeatMax'] },
  { id: '13', name: 'VICTIM_CASTING', label: 'Victim Casting', params: ['RepeatMin', 'RepeatMax', 'SpellID'] },
  { id: '14', name: 'FRIENDLY_HEALTH', label: 'Friendly Health', params: ['HPDeficit', 'Radius', 'RepeatMin', 'RepeatMax'] },
  { id: '15', name: 'FRIENDLY_IS_CC', label: 'Friendly Is Crowd Controlled', params: ['Radius', 'RepeatMin', 'RepeatMax'] },
  { id: '16', name: 'FRIENDLY_MISSING_BUFF', label: 'Friendly Missing Buff', params: ['SpellID', 'Radius', 'RepeatMin', 'RepeatMax'] },
  { id: '17', name: 'SUMMONED_UNIT', label: 'Summoned Unit', params: ['CreatureID', 'CooldownMin', 'CooldownMax'] },
  { id: '18', name: 'TARGET_MANA_PCT', label: 'Target Mana Percentage', params: ['ManaMin%', 'ManaMax%', 'RepeatMin', 'RepeatMax'] },
  { id: '19', name: 'ACCEPTED_QUEST', label: 'Quest Accepted', params: ['QuestID'] },
  { id: '20', name: 'REWARD_QUEST', label: 'Quest Rewarded', params: ['QuestID'] },
  { id: '21', name: 'REACHED_HOME', label: 'Reached Home', params: [] },
  { id: '22', name: 'RECEIVE_EMOTE', label: 'Receive Emote', params: ['EmoteID', 'CooldownMin', 'CooldownMax'] },
  { id: '23', name: 'HAS_AURA', label: 'Has Aura', params: ['SpellID', 'StackCount', 'RepeatMin', 'RepeatMax'] },
  { id: '24', name: 'TARGET_BUFFED', label: 'Target Buffed', params: ['SpellID', 'StackCount', 'RepeatMin', 'RepeatMax'] },
  { id: '25', name: 'RESET', label: 'On Reset', params: [] },
  { id: '26', name: 'IC_LOS', label: 'IC Line of Sight', params: ['HostileCrew', 'MaxRange', 'CooldownMin', 'CooldownMax'] },
  { id: '27', name: 'PASSENGER_BOARDED', label: 'Passenger Boarded', params: ['CooldownMin', 'CooldownMax'] },
  { id: '28', name: 'PASSENGER_REMOVED', label: 'Passenger Removed', params: ['CooldownMin', 'CooldownMax'] },
  { id: '29', name: 'CHARMED', label: 'On Charmed', params: ['OnRemove'] },
  { id: '30', name: 'CHARMED_TARGET', label: 'Charmed Target', params: ['OnRemove'] },
  { id: '31', name: 'SPELLHIT_TARGET', label: 'Spell Hit Target', params: ['SpellID', 'School', 'CooldownMin', 'CooldownMax'] },
  { id: '32', name: 'DAMAGED', label: 'On Damaged', params: ['MinDmg', 'MaxDmg', 'RepeatMin', 'RepeatMax'] },
  { id: '33', name: 'DAMAGED_TARGET', label: 'Target Damaged', params: ['MinDmg', 'MaxDmg', 'RepeatMin', 'RepeatMax'] },
  { id: '34', name: 'MOVEMENTINFORM', label: 'Movement Inform', params: ['MovementType', 'PointID'] },
  { id: '35', name: 'SUMMON_DESPAWNED', label: 'Summon Despawned', params: ['CreatureID', 'CooldownMin', 'CooldownMax'] },
  { id: '36', name: 'CORPSE_REMOVED', label: 'Corpse Removed', params: [] },
  { id: '37', name: 'AI_INIT', label: 'AI Initialize', params: [] },
  { id: '38', name: 'DATA_SET', label: 'Data Set', params: ['Field', 'Value', 'CooldownMin', 'CooldownMax'] },
  { id: '39', name: 'WAYPOINT_START', label: 'Waypoint Start', params: ['PointID', 'PathID'] },
  { id: '40', name: 'WAYPOINT_REACHED', label: 'Waypoint Reached', params: ['PointID', 'PathID'] },
  { id: '41', name: 'TRANSPORT_ADDPLAYER', label: 'Transport Add Player', params: [] },
  { id: '42', name: 'TRANSPORT_ADDCREATURE', label: 'Transport Add Creature', params: ['CreatureID'] },
  { id: '43', name: 'TRANSPORT_REMOVE_PLAYER', label: 'Transport Remove Player', params: [] },
  { id: '44', name: 'TRANSPORT_RELOCATE', label: 'Transport Relocate', params: ['PointID'] },
  { id: '45', name: 'INSTANCE_PLAYER_ENTER', label: 'Instance Player Enter', params: [] },
  { id: '46', name: 'AREATRIGGER_ENTER', label: 'Areatrigger Enter', params: ['AreaTriggerID'] },
  { id: '47', name: 'QUEST_ACCEPTED', label: 'Quest Accepted', params: ['QuestID'] },
  { id: '48', name: 'QUEST_OBJ_COMPLETION', label: 'Quest Objective Completion', params: ['QuestID'] },
  { id: '49', name: 'QUEST_COMPLETION', label: 'Quest Completion', params: ['QuestID'] },
  { id: '50', name: 'QUEST_REWARDED', label: 'Quest Rewarded', params: ['QuestID'] },
  { id: '51', name: 'QUEST_FAIL', label: 'Quest Failed', params: ['QuestID'] },
  { id: '52', name: 'TEXT_OVER', label: 'Text Over', params: ['GroupID', 'CreatureID'] },
  { id: '53', name: 'RECEIVE_HEAL', label: 'Receive Heal', params: ['MinHeal', 'MaxHeal', 'RepeatMin', 'RepeatMax'] },
  { id: '54', name: 'JUST_SUMMONED', label: 'Just Summoned', params: [] },
  { id: '55', name: 'WAYPOINT_PAUSED', label: 'Waypoint Paused', params: ['PointID', 'PathID'] },
  { id: '56', name: 'WAYPOINT_RESUMED', label: 'Waypoint Resumed', params: ['PointID', 'PathID'] },
  { id: '57', name: 'WAYPOINT_STOPPED', label: 'Waypoint Stopped', params: ['PointID', 'PathID'] },
  { id: '58', name: 'WAYPOINT_ENDED', label: 'Waypoint Ended', params: ['PointID', 'PathID'] },
  { id: '59', name: 'TIMED_EVENT_TRIGGERED', label: 'Timed Event Triggered', params: ['EventID'] },
  { id: '60', name: 'UPDATE', label: 'Update (Always)', params: ['InitialMin', 'InitialMax', 'RepeatMin', 'RepeatMax'] },
  { id: '61', name: 'LINK', label: 'Link', params: [] },
  { id: '62', name: 'GOSSIP_SELECT', label: 'Gossip Select', params: ['MenuID', 'OptionID'] },
  { id: '63', name: 'JUST_CREATED', label: 'Just Created', params: [] },
  { id: '64', name: 'GOSSIP_HELLO', label: 'Gossip Hello', params: [] },
  { id: '65', name: 'FOLLOW_COMPLETED', label: 'Follow Completed', params: [] },
  { id: '66', name: 'EVENT_PHASE_CHANGE', label: 'Event Phase Change', params: ['FromPhase', 'ToPhase'] },
  { id: '67', name: 'IS_BEHIND_TARGET', label: 'Is Behind Target', params: ['CooldownMin', 'CooldownMax'] },
  { id: '68', name: 'GAME_EVENT_START', label: 'Game Event Start', params: ['EventID'] },
  { id: '69', name: 'GAME_EVENT_END', label: 'Game Event End', params: ['EventID'] },
  { id: '70', name: 'GO_LOOT_STATE_CHANGED', label: 'GO Loot State Changed', params: ['State'] },
  { id: '71', name: 'GO_EVENT_INFORM', label: 'GO Event Inform', params: ['EventID'] },
  { id: '72', name: 'ACTION_DONE', label: 'Action Done', params: ['EventID'] },
  { id: '73', name: 'ON_SPELLCLICK', label: 'On Spellclick', params: [] },
  { id: '74', name: 'FRIENDLY_HEALTH_PCT', label: 'Friendly Health PCT', params: ['HPMin%', 'HPMax%', 'RepeatMin', 'RepeatMax'] },
  { id: '75', name: 'DISTANCE_CREATURE', label: 'Distance Creature', params: ['CreatureID', 'Distance', 'RepeatMin', 'RepeatMax'] },
  { id: '76', name: 'DISTANCE_GAMEOBJECT', label: 'Distance Gameobject', params: ['GameobjectID', 'Distance', 'RepeatMin', 'RepeatMax'] },
  { id: '77', name: 'COUNTER_SET', label: 'Counter Set', params: ['CounterID', 'Value', 'CooldownMin', 'CooldownMax'] },
  { id: '78', name: 'SCENE_START', label: 'Scene Start', params: [] },
  { id: '79', name: 'SCENE_TRIGGER', label: 'Scene Trigger', params: [] },
  { id: '80', name: 'SCENE_CANCEL', label: 'Scene Cancel', params: [] },
  { id: '81', name: 'SCENE_COMPLETE', label: 'Scene Complete', params: [] },
  { id: '82', name: 'SUMMONED_UNIT_DIES', label: 'Summoned Unit Dies', params: ['CreatureID', 'CooldownMin', 'CooldownMax'] },
  { id: '83', name: 'ON_SPELL_CAST', label: 'On Spell Cast', params: ['SpellID', 'CooldownMin', 'CooldownMax'] },
  { id: '84', name: 'ON_SPELL_FAILED', label: 'On Spell Failed', params: ['SpellID', 'CooldownMin', 'CooldownMax'] },
  { id: '85', name: 'ON_SPELL_START', label: 'On Spell Start', params: ['SpellID', 'CooldownMin', 'CooldownMax'] },
  { id: '86', name: 'ON_DESPAWN', label: 'On Despawn', params: [] },
  { id: '87', name: 'SEND_EVENT_TRIGGER', label: 'Send Event Trigger', params: ['EventID'] },
  { id: '88', name: 'AREATRIGGER_EXIT', label: 'Areatrigger Exit', params: ['AreaTriggerID'] },
  { id: '89', name: 'ON_AURA_APPLIED', label: 'On Aura Applied', params: ['SpellID'] },
  { id: '90', name: 'ON_AURA_REMOVED', label: 'On Aura Removed', params: ['SpellID'] },
];

/**
 * COMPLETE SAI Action Types (0-159) - ALL TrinityCore Actions
 */
export const SAI_ACTION_TYPES_COMPLETE = [
  { id: '0', name: 'NONE', label: 'None', params: [] },
  { id: '1', name: 'TALK', label: 'Say Text', params: ['TextID', 'Duration', 'UseTalkTarget'] },
  { id: '2', name: 'SET_FACTION', label: 'Set Faction', params: ['FactionID'] },
  { id: '3', name: 'MORPH_TO_ENTRY_OR_MODEL', label: 'Morph', params: ['CreatureEntry', 'ModelID'] },
  { id: '4', name: 'SOUND', label: 'Play Sound', params: ['SoundID', 'OnlySelf', 'Distance'] },
  { id: '5', name: 'PLAY_EMOTE', label: 'Play Emote', params: ['EmoteID'] },
  { id: '6', name: 'FAIL_QUEST', label: 'Fail Quest', params: ['QuestID'] },
  { id: '7', name: 'OFFER_QUEST', label: 'Offer Quest', params: ['QuestID', 'DirectAdd'] },
  { id: '8', name: 'SET_REACT_STATE', label: 'Set React State', params: ['State'] },
  { id: '9', name: 'ACTIVATE_GOBJECT', label: 'Activate Gameobject', params: [] },
  { id: '10', name: 'RANDOM_EMOTE', label: 'Random Emote', params: ['Emote1', 'Emote2', 'Emote3', 'Emote4'] },
  { id: '11', name: 'CAST', label: 'Cast Spell', params: ['SpellID', 'CastFlags', 'TriggerFlags'] },
  { id: '12', name: 'SUMMON_CREATURE', label: 'Summon Creature', params: ['CreatureEntry', 'SummonType', 'Duration', 'AttackInvoker'] },
  { id: '13', name: 'THREAT_SINGLE_PCT', label: 'Threat Single PCT', params: ['ThreatPCT', 'IncDec'] },
  { id: '14', name: 'THREAT_ALL_PCT', label: 'Threat All PCT', params: ['ThreatPCT', 'IncDec'] },
  { id: '15', name: 'CALL_AREAEXPLOREDOREVENTHAPPENS', label: 'Call Area Explored or Event Happens', params: ['QuestID'] },
  { id: '16', name: 'SET_INGAME_PHASE_GROUP', label: 'Set Ingame Phase Group', params: ['GroupID', 'Apply'] },
  { id: '17', name: 'SET_EMOTE_STATE', label: 'Set Emote State', params: ['EmoteID'] },
  { id: '18', name: 'SET_UNIT_FLAG', label: 'Set Unit Flag', params: ['Flags'] },
  { id: '19', name: 'REMOVE_UNIT_FLAG', label: 'Remove Unit Flag', params: ['Flags'] },
  { id: '20', name: 'AUTO_ATTACK', label: 'Auto Attack', params: ['AllowAttackState'] },
  { id: '21', name: 'ALLOW_COMBAT_MOVEMENT', label: 'Allow Combat Movement', params: ['AllowMovement'] },
  { id: '22', name: 'SET_EVENT_PHASE', label: 'Set Event Phase', params: ['Phase'] },
  { id: '23', name: 'INC_EVENT_PHASE', label: 'Inc Event Phase', params: ['Increment', 'Decrement'] },
  { id: '24', name: 'EVADE', label: 'Evade', params: [] },
  { id: '25', name: 'FLEE_FOR_ASSIST', label: 'Flee For Assist', params: [] },
  { id: '26', name: 'CALL_GROUPEVENTHAPPENS', label: 'Call Group Event Happens', params: ['QuestID'] },
  { id: '27', name: 'COMBAT_STOP', label: 'Combat Stop', params: [] },
  { id: '28', name: 'REMOVEAURASFROMSPELL', label: 'Remove Auras From Spell', params: ['SpellID', 'Charges'] },
  { id: '29', name: 'FOLLOW', label: 'Follow', params: ['Distance', 'Angle', 'EndCreatureEntry'] },
  { id: '30', name: 'RANDOM_PHASE', label: 'Random Phase', params: ['Phase1', 'Phase2', 'Phase3', 'Phase4'] },
  { id: '31', name: 'RANDOM_PHASE_RANGE', label: 'Random Phase Range', params: ['PhaseMin', 'PhaseMax'] },
  { id: '32', name: 'RESET_GOBJECT', label: 'Reset Gameobject', params: [] },
  { id: '33', name: 'CALL_KILLEDMONSTER', label: 'Call Killed Monster', params: ['CreatureEntry'] },
  { id: '34', name: 'SET_INST_DATA', label: 'Set Instance Data', params: ['Field', 'Data'] },
  { id: '35', name: 'SET_INST_DATA64', label: 'Set Instance Data64', params: ['Field'] },
  { id: '36', name: 'UPDATE_TEMPLATE', label: 'Update Template', params: ['Entry', 'Team'] },
  { id: '37', name: 'DIE', label: 'Force Die', params: [] },
  { id: '38', name: 'SET_IN_COMBAT_WITH_ZONE', label: 'Set In Combat With Zone', params: [] },
  { id: '39', name: 'CALL_FOR_HELP', label: 'Call For Help', params: ['Radius'] },
  { id: '40', name: 'SET_SHEATH', label: 'Set Sheath', params: ['Sheath'] },
  { id: '41', name: 'FORCE_DESPAWN', label: 'Force Despawn', params: ['Delay'] },
  { id: '42', name: 'SET_INVINCIBILITY_HP_LEVEL', label: 'Set Invincibility HP Level', params: ['MinHP', 'Percent'] },
  { id: '43', name: 'MOUNT_TO_ENTRY_OR_MODEL', label: 'Mount', params: ['CreatureEntry', 'ModelID'] },
  { id: '44', name: 'SET_INGAME_PHASE_ID', label: 'Set Ingame Phase ID', params: ['ID', 'Apply'] },
  { id: '45', name: 'SET_DATA', label: 'Set Data', params: ['Field', 'Data'] },
  { id: '46', name: 'ATTACK_STOP', label: 'Attack Stop', params: [] },
  { id: '47', name: 'SET_VISIBILITY', label: 'Set Visibility', params: ['Visibility'] },
  { id: '48', name: 'SET_ACTIVE', label: 'Set Active', params: ['Active'] },
  { id: '49', name: 'ATTACK_START', label: 'Attack Start', params: [] },
  { id: '50', name: 'SUMMON_GO', label: 'Summon Gameobject', params: ['GameobjectEntry', 'DespawnTime'] },
  { id: '51', name: 'KILL_UNIT', label: 'Kill Unit', params: [] },
  { id: '52', name: 'ACTIVATE_TAXI', label: 'Activate Taxi', params: ['TaxiID'] },
  { id: '53', name: 'WP_START', label: 'Waypoint Start', params: ['Run', 'PathID', 'Repeat', 'Quest'] },
  { id: '54', name: 'WP_PAUSE', label: 'Waypoint Pause', params: ['Time'] },
  { id: '55', name: 'WP_STOP', label: 'Waypoint Stop', params: ['DespawnTime', 'Quest', 'Fail'] },
  { id: '56', name: 'ADD_ITEM', label: 'Add Item', params: ['ItemID', 'Count'] },
  { id: '57', name: 'REMOVE_ITEM', label: 'Remove Item', params: ['ItemID', 'Count'] },
  { id: '58', name: 'INSTALL_AI_TEMPLATE', label: 'Install AI Template', params: ['TemplateID'] },
  { id: '59', name: 'SET_RUN', label: 'Set Run', params: ['Run'] },
  { id: '60', name: 'SET_DISABLE_GRAVITY', label: 'Set Disable Gravity', params: ['Disable'] },
  { id: '61', name: 'SET_SWIM', label: 'Set Swim', params: ['Swim'] },
  { id: '62', name: 'TELEPORT', label: 'Teleport', params: ['MapID'] },
  { id: '63', name: 'SET_COUNTER', label: 'Set Counter', params: ['CounterID', 'Value', 'Reset'] },
  { id: '64', name: 'STORE_TARGET_LIST', label: 'Store Target List', params: ['ID'] },
  { id: '65', name: 'WP_RESUME', label: 'Waypoint Resume', params: [] },
  { id: '66', name: 'SET_ORIENTATION', label: 'Set Orientation', params: ['Orientation'] },
  { id: '67', name: 'CREATE_TIMED_EVENT', label: 'Create Timed Event', params: ['ID', 'InitMin', 'InitMax', 'RepeatMin'] },
  { id: '68', name: 'PLAYMOVIE', label: 'Play Movie', params: ['MovieID'] },
  { id: '69', name: 'MOVE_TO_POS', label: 'Move To Position', params: ['X', 'Y', 'Z', 'O'] },
  { id: '70', name: 'ENABLE_TEMP_GOBJ', label: 'Enable Temp Gameobject', params: ['Duration'] },
  { id: '71', name: 'EQUIP', label: 'Equip', params: ['EquipmentID'] },
  { id: '72', name: 'CLOSE_GOSSIP', label: 'Close Gossip', params: [] },
  { id: '73', name: 'TRIGGER_TIMED_EVENT', label: 'Trigger Timed Event', params: ['ID'] },
  { id: '74', name: 'REMOVE_TIMED_EVENT', label: 'Remove Timed Event', params: ['ID'] },
  { id: '75', name: 'ADD_AURA', label: 'Add Aura', params: ['SpellID'] },
  { id: '76', name: 'OVERRIDE_SCRIPT_BASE_OBJECT', label: 'Override Script Base Object', params: [] },
  { id: '77', name: 'RESET_SCRIPT_BASE_OBJECT', label: 'Reset Script Base Object', params: [] },
  { id: '78', name: 'CALL_SCRIPT_RESET', label: 'Call Script Reset', params: [] },
  { id: '79', name: 'SET_RANGED_MOVEMENT', label: 'Set Ranged Movement', params: ['Distance', 'Angle'] },
  { id: '80', name: 'CALL_TIMED_ACTIONLIST', label: 'Call Timed Actionlist', params: ['ID'] },
  { id: '81', name: 'SET_NPC_FLAG', label: 'Set NPC Flag', params: ['Flags'] },
  { id: '82', name: 'ADD_NPC_FLAG', label: 'Add NPC Flag', params: ['Flags'] },
  { id: '83', name: 'REMOVE_NPC_FLAG', label: 'Remove NPC Flag', params: ['Flags'] },
  { id: '84', name: 'SIMPLE_TALK', label: 'Simple Talk', params: ['TextID'] },
  { id: '85', name: 'SELF_CAST', label: 'Self Cast', params: ['SpellID'] },
  { id: '86', name: 'CROSS_CAST', label: 'Cross Cast', params: ['SpellID', 'Flags'] },
  { id: '87', name: 'CALL_RANDOM_TIMED_ACTIONLIST', label: 'Call Random Timed Actionlist', params: ['ID1', 'ID2', 'ID3'] },
  { id: '88', name: 'CALL_RANDOM_RANGE_TIMED_ACTIONLIST', label: 'Call Random Range Timed Actionlist', params: ['IDMin', 'IDMax'] },
  { id: '89', name: 'RANDOM_MOVE', label: 'Random Move', params: ['Distance'] },
  { id: '90', name: 'SET_UNIT_FIELD_BYTES_1', label: 'Set Unit Field Bytes 1', params: ['Bytes', 'Type'] },
  { id: '91', name: 'REMOVE_UNIT_FIELD_BYTES_1', label: 'Remove Unit Field Bytes 1', params: ['Bytes', 'Type'] },
  { id: '92', name: 'INTERRUPT_SPELL', label: 'Interrupt Spell', params: [] },
  { id: '93', name: 'SEND_GO_CUSTOM_ANIM', label: 'Send GO Custom Anim', params: ['AnimID'] },
  { id: '94', name: 'SET_DYNAMIC_FLAG', label: 'Set Dynamic Flag', params: ['Flags'] },
  { id: '95', name: 'ADD_DYNAMIC_FLAG', label: 'Add Dynamic Flag', params: ['Flags'] },
  { id: '96', name: 'REMOVE_DYNAMIC_FLAG', label: 'Remove Dynamic Flag', params: ['Flags'] },
  { id: '97', name: 'JUMP_TO_POS', label: 'Jump To Position', params: ['SpeedXY', 'SpeedZ', 'X', 'Y', 'Z'] },
  { id: '98', name: 'SEND_GOSSIP_MENU', label: 'Send Gossip Menu', params: ['MenuID', 'OptionID'] },
  { id: '99', name: 'GO_SET_LOOT_STATE', label: 'GO Set Loot State', params: ['State'] },
  { id: '100', name: 'SEND_TARGET_TO_TARGET', label: 'Send Target To Target', params: ['ID'] },
  { id: '101', name: 'SET_HOME_POS', label: 'Set Home Position', params: [] },
  { id: '102', name: 'SET_HEALTH_REGEN', label: 'Set Health Regen', params: ['Regen'] },
  { id: '103', name: 'SET_ROOT', label: 'Set Root', params: ['Root'] },
  { id: '104', name: 'SET_GO_FLAG', label: 'Set GO Flag', params: ['Flags'] },
  { id: '105', name: 'ADD_GO_FLAG', label: 'Add GO Flag', params: ['Flags'] },
  { id: '106', name: 'REMOVE_GO_FLAG', label: 'Remove GO Flag', params: ['Flags'] },
  { id: '107', name: 'SUMMON_CREATURE_GROUP', label: 'Summon Creature Group', params: ['GroupID', 'AttackInvoker'] },
  { id: '108', name: 'SET_POWER', label: 'Set Power', params: ['PowerType', 'Power'] },
  { id: '109', name: 'ADD_POWER', label: 'Add Power', params: ['PowerType', 'Power'] },
  { id: '110', name: 'REMOVE_POWER', label: 'Remove Power', params: ['PowerType', 'Power'] },
  { id: '111', name: 'GAME_EVENT_STOP', label: 'Game Event Stop', params: ['EventID'] },
  { id: '112', name: 'GAME_EVENT_START', label: 'Game Event Start', params: ['EventID'] },
  { id: '113', name: 'START_CLOSEST_WAYPOINT', label: 'Start Closest Waypoint', params: ['WP1', 'WP2', 'WP3', 'WP4'] },
  { id: '114', name: 'MOVE_OFFSET', label: 'Move Offset', params: ['X', 'Y', 'Z'] },
  { id: '115', name: 'RANDOM_SOUND', label: 'Random Sound', params: ['Sound1', 'Sound2', 'Sound3', 'Sound4'] },
  { id: '116', name: 'SET_CORPSE_DELAY', label: 'Set Corpse Delay', params: ['Timer'] },
  { id: '117', name: 'DISABLE_EVADE', label: 'Disable Evade', params: ['Disable'] },
  { id: '118', name: 'GO_SET_GO_STATE', label: 'GO Set GO State', params: ['State'] },
  { id: '119', name: 'SET_CAN_FLY', label: 'Set Can Fly', params: ['Fly'] },
  { id: '120', name: 'REMOVE_AURAS_BY_TYPE', label: 'Remove Auras By Type', params: ['AuraType'] },
  { id: '121', name: 'SET_SIGHT_DIST', label: 'Set Sight Distance', params: ['Distance'] },
  { id: '122', name: 'FLEE', label: 'Flee', params: ['FleeTime'] },
  { id: '123', name: 'ADD_THREAT', label: 'Add Threat', params: ['Threat'] },
  { id: '124', name: 'LOAD_EQUIPMENT', label: 'Load Equipment', params: ['ID', 'Force'] },
  { id: '125', name: 'TRIGGER_RANDOM_TIMED_EVENT', label: 'Trigger Random Timed Event', params: ['ID1', 'ID2', 'ID3'] },
  { id: '126', name: 'REMOVE_ALL_GAMEOBJECTS', label: 'Remove All Gameobjects', params: [] },
  { id: '127', name: 'PAUSE_MOVEMENT', label: 'Pause Movement', params: ['PauseTimer', 'Force'] },
  { id: '128', name: 'PLAY_ANIMKIT', label: 'Play Animkit', params: ['AnimKitID', 'Type'] },
  { id: '129', name: 'SCENE_PLAY', label: 'Scene Play', params: ['SceneID'] },
  { id: '130', name: 'SCENE_CANCEL', label: 'Scene Cancel', params: ['SceneID'] },
  { id: '131', name: 'SPAWN_SPAWNGROUP', label: 'Spawn Spawngroup', params: ['GroupID', 'MinDelay', 'MaxDelay'] },
  { id: '132', name: 'DESPAWN_SPAWNGROUP', label: 'Despawn Spawngroup', params: ['GroupID', 'MinDelay', 'MaxDelay'] },
  { id: '133', name: 'RESPAWN_BY_SPAWNID', label: 'Respawn By SpawnID', params: ['Type', 'SpawnID'] },
  { id: '134', name: 'INVOKER_CAST', label: 'Invoker Cast', params: ['SpellID', 'CastFlags'] },
  { id: '135', name: 'PLAY_CINEMATIC', label: 'Play Cinematic', params: ['CinematicID'] },
  { id: '136', name: 'SET_MOVEMENT_SPEED', label: 'Set Movement Speed', params: ['SpeedType', 'Speed'] },
  { id: '137', name: 'PLAY_SPELL_VISUAL_KIT', label: 'Play Spell Visual Kit', params: ['KitID', 'Type', 'Duration'] },
  { id: '138', name: 'OVERRIDE_LIGHT', label: 'Override Light', params: ['ZoneID', 'AreaLightID', 'TransitionTime'] },
  { id: '139', name: 'OVERRIDE_WEATHER', label: 'Override Weather', params: ['ZoneID', 'WeatherType', 'Grade'] },
  { id: '140', name: 'SET_AI_ANIM_KIT', label: 'Set AI Anim Kit', params: ['AnimKitID'] },
  { id: '141', name: 'SET_HOVER', label: 'Set Hover', params: ['Enable'] },
  { id: '142', name: 'SET_HEALTH_PCT', label: 'Set Health PCT', params: ['Percent'] },
  { id: '143', name: 'CREATE_CONVERSATION', label: 'Create Conversation', params: ['ConversationID'] },
  { id: '144', name: 'SET_IMMUNE_PC', label: 'Set Immune PC', params: ['Immune'] },
  { id: '145', name: 'SET_IMMUNE_NPC', label: 'Set Immune NPC', params: ['Immune'] },
  { id: '146', name: 'SET_UNINTERACTIBLE', label: 'Set Uninteractible', params: ['Uninteractible'] },
  { id: '147', name: 'ACTIVATE_GAMEOBJECT', label: 'Activate Gameobject', params: [] },
  { id: '148', name: 'ADD_TO_STORED_TARGET_LIST', label: 'Add To Stored Target List', params: ['ID'] },
  { id: '149', name: 'BECOME_PERSONAL_CLONE_FOR_PLAYER', label: 'Become Personal Clone For Player', params: ['Type', 'Duration'] },
  { id: '150', name: 'TRIGGER_GAME_EVENT', label: 'Trigger Game Event', params: ['EventID', 'UseSAITargetAsGameEventSource'] },
  { id: '151', name: 'DO_ACTION', label: 'Do Action', params: ['ActionID'] },
  { id: '152', name: 'COMPLETE_QUEST', label: 'Complete Quest', params: ['QuestID'] },
  { id: '153', name: 'CREDIT_QUEST_OBJECTIVE_TALK_TO', label: 'Credit Quest Objective Talk To', params: ['QuestID', 'ObjectiveID'] },
  { id: '154', name: 'DESTROY_CONVERSATION', label: 'Destroy Conversation', params: ['ConversationID'] },
  { id: '155', name: 'ENTER_VEHICLE', label: 'Enter Vehicle', params: ['VehicleSeat'] },
  { id: '156', name: 'BOARD_PASSENGER', label: 'Board Passenger', params: ['VehicleEntry', 'VehicleSeat'] },
  { id: '157', name: 'EXIT_VEHICLE', label: 'Exit Vehicle', params: [] },
  { id: '158', name: 'RESUME_MOVEMENT', label: 'Resume Movement', params: [] },
  { id: '159', name: 'FALL', label: 'Fall', params: [] },
];

/**
 * COMPLETE SAI Target Types (0-30) - ALL TrinityCore Targets
 */
export const SAI_TARGET_TYPES_COMPLETE = [
  { id: '0', name: 'NONE', label: 'No Target', params: [] },
  { id: '1', name: 'SELF', label: 'Self', params: [] },
  { id: '2', name: 'VICTIM', label: 'Current Victim', params: [] },
  { id: '3', name: 'HOSTILE_SECOND_AGGRO', label: 'Second Aggro', params: [] },
  { id: '4', name: 'HOSTILE_LAST_AGGRO', label: 'Last Aggro', params: [] },
  { id: '5', name: 'HOSTILE_RANDOM', label: 'Random Target', params: ['MaxDist'] },
  { id: '6', name: 'HOSTILE_RANDOM_NOT_TOP', label: 'Random Not Top', params: ['MaxDist'] },
  { id: '7', name: 'ACTION_INVOKER', label: 'Action Invoker', params: [] },
  { id: '8', name: 'POSITION', label: 'Position', params: [] },
  { id: '9', name: 'CREATURE_RANGE', label: 'Creature in Range', params: ['CreatureEntry', 'MinDist', 'MaxDist'] },
  { id: '10', name: 'CREATURE_GUID', label: 'Creature by GUID', params: ['GUID', 'Entry'] },
  { id: '11', name: 'CREATURE_DISTANCE', label: 'Creature by Distance', params: ['CreatureEntry', 'MaxDist'] },
  { id: '12', name: 'STORED', label: 'Stored Target', params: ['ID'] },
  { id: '13', name: 'GAMEOBJECT_RANGE', label: 'Gameobject in Range', params: ['GameobjectEntry', 'MinDist', 'MaxDist'] },
  { id: '14', name: 'GAMEOBJECT_GUID', label: 'Gameobject by GUID', params: ['GUID', 'Entry'] },
  { id: '15', name: 'GAMEOBJECT_DISTANCE', label: 'Gameobject by Distance', params: ['GameobjectEntry', 'MaxDist'] },
  { id: '16', name: 'INVOKER_PARTY', label: 'Invoker Party', params: [] },
  { id: '17', name: 'PLAYER_RANGE', label: 'Player in Range', params: ['MinDist', 'MaxDist'] },
  { id: '18', name: 'PLAYER_DISTANCE', label: 'Player by Distance', params: ['MaxDist'] },
  { id: '19', name: 'CLOSEST_CREATURE', label: 'Closest Creature', params: ['CreatureEntry', 'MaxDist', 'Alive'] },
  { id: '20', name: 'CLOSEST_GAMEOBJECT', label: 'Closest Gameobject', params: ['GameobjectEntry', 'MaxDist'] },
  { id: '21', name: 'CLOSEST_PLAYER', label: 'Closest Player', params: ['MaxDist'] },
  { id: '22', name: 'ACTION_INVOKER_VEHICLE', label: 'Invoker Vehicle', params: [] },
  { id: '23', name: 'OWNER_OR_SUMMONER', label: 'Owner or Summoner', params: [] },
  { id: '24', name: 'THREAT_LIST', label: 'Threat List', params: [] },
  { id: '25', name: 'CLOSEST_ENEMY', label: 'Closest Enemy', params: ['MaxDist', 'PlayerOnly'] },
  { id: '26', name: 'CLOSEST_FRIENDLY', label: 'Closest Friendly', params: ['MaxDist', 'PlayerOnly'] },
  { id: '27', name: 'LOOT_RECIPIENTS', label: 'Loot Recipients', params: [] },
  { id: '28', name: 'FARTHEST', label: 'Farthest', params: ['MaxDist'] },
  { id: '29', name: 'VEHICLE_PASSENGER', label: 'Vehicle Passenger', params: ['SeatID'] },
  { id: '30', name: 'CLOSEST_UNSPAWNED_GAMEOBJECT', label: 'Closest Unspawned Gameobject', params: ['GameobjectEntry', 'MaxDist'] },
];
